use_frameworks!

platform :ios, '8.0'

- source 'https://github.com/CocoaPods/Specs.git'
+ source 'https://cdn.cocoapods.org/'

target 'LvMessageModule_Example' do
  pod 'LvMessageModule', :path => '../'

  target 'LvMessageModule_Tests' do
    inherit! :search_paths

    
  end
end
