// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Eim_constant.pb.h"
// @@protoc_insertion_point(imports)

@implementation EimConstantRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EimConstantRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL EIM_CMD_TYPEIsValidValue(EIM_CMD_TYPE value) {
  switch (value) {
    case EIM_CMD_TYPEEimCmdAuth:
    case EIM_CMD_TYPEEimCmdHeartbeat:
    case EIM_CMD_TYPEEimCmdMessage:
    case EIM_CMD_TYPEEimCmdGroupMessage:
    case EIM_CMD_TYPEEimCmdPullMessage:
    case EIM_CMD_TYPEDeviceReconnectionAuth:
    case EIM_CMD_TYPEEimUserMsgNotification:
    case EIM_CMD_TYPEEimUserAddBlackList:
    case EIM_CMD_TYPEEimCreateGroup:
    case EIM_CMD_TYPEEimInviteJoinGroup:
    case EIM_CMD_TYPEEimRemoveFromGroup:
    case EIM_CMD_TYPEEimGroupOwnerTransfer:
    case EIM_CMD_TYPEEimAddGroupManager:
    case EIM_CMD_TYPEEimAddGroupAnnouncement:
    case EIM_CMD_TYPEEimSetGroupName:
    case EIM_CMD_TYPEEimSetGroupUserNickname:
    case EIM_CMD_TYPEEimQuitGroup:
    case EIM_CMD_TYPEEimVoipCreateToken:
    case EIM_CMD_TYPEEimCreateVoipSolo:
    case EIM_CMD_TYPEEimCreateVoipGroup:
    case EIM_CMD_TYPEEimJoinVoip:
    case EIM_CMD_TYPEEimRefuseVoip:
    case EIM_CMD_TYPEEimCancelVoip:
    case EIM_CMD_TYPEEimHangupVoip:
    case EIM_CMD_TYPEEimBusyVoip:
    case EIM_CMD_TYPEEimAgroaConnectedVoip:
    case EIM_CMD_TYPEEimVoipBroadcastAck:
    case EIM_CMD_TYPEEimJoinVoipBroadcastAck:
    case EIM_CMD_TYPEEimRefuseVoipBroadcastAck:
    case EIM_CMD_TYPEEimCancelVoipBroadcastAck:
    case EIM_CMD_TYPEEimHangupVoipBroadcastAck:
    case EIM_CMD_TYPEEimReportRunStatus:
    case EIM_CMD_TYPEEimJoinGroup:
    case EIM_CMD_TYPEEimSetGroupNotificaton:
    case EIM_CMD_TYPEEimDeleteGroupManager:
    case EIM_CMD_TYPEAuthAck:
    case EIM_CMD_TYPEHeaetbeatAck:
    case EIM_CMD_TYPESendMessageAck:
    case EIM_CMD_TYPEPullMessageAck:
    case EIM_CMD_TYPEPullSequenceAck:
    case EIM_CMD_TYPEUserMsgNotificationAck:
    case EIM_CMD_TYPEUserAddBlackListAck:
    case EIM_CMD_TYPEReportRunStatusAck:
    case EIM_CMD_TYPECreateGroupAck:
    case EIM_CMD_TYPEUpdateGroupRemarkAck:
    case EIM_CMD_TYPEUpdateGroupNameAck:
    case EIM_CMD_TYPEJoinGroupAck:
    case EIM_CMD_TYPEUpdateGroupNicknameAck:
    case EIM_CMD_TYPEQuitGroupAck:
    case EIM_CMD_TYPEAddGroupMangerAck:
    case EIM_CMD_TYPEInviteJoinGroupAck:
    case EIM_CMD_TYPERemoveFromGroupAck:
    case EIM_CMD_TYPEGroupOwnerTransferAck:
    case EIM_CMD_TYPEDeviceReconnectionAuthAck:
    case EIM_CMD_TYPESetGroupNotificationAck:
    case EIM_CMD_TYPEDeleteGroupManagerAck:
    case EIM_CMD_TYPEEimNotifyNewMsgPush:
    case EIM_CMD_TYPEEimCreateGroupBroadcase:
    case EIM_CMD_TYPEEimJoinGroupBroadcase:
    case EIM_CMD_TYPEEimQuitGroupBroadcase:
    case EIM_CMD_TYPEEimSetManagerGroupBroadcase:
    case EIM_CMD_TYPEEimOwnerTranserBroadcase:
    case EIM_CMD_TYPEEimGroupRenameBroadcase:
    case EIM_CMD_TYPEEimOwnerQuitGroupBroadcase:
    case EIM_CMD_TYPEEimDeleteUserGroupBroadcase:
    case EIM_CMD_TYPEEimSoloVoipBroadcast:
    case EIM_CMD_TYPEEimGroupVoipBroadcast:
    case EIM_CMD_TYPEEimUserJoinVoipBroadcast:
    case EIM_CMD_TYPEEimRefuseVoipBroadcast:
    case EIM_CMD_TYPEEimCancelVoipBroadcast:
    case EIM_CMD_TYPEEimHangupVoipBroadcast:
    case EIM_CMD_TYPEEimBusyToVoipBroadcast:
    case EIM_CMD_TYPEEimAgoraConnectedVoipBroadcast:
    case EIM_CMD_TYPEEimOwnerDeleteGroupBroadcast:
    case EIM_CMD_TYPEEimGroupRemarkUpdateBroadcast:
      return YES;
    default:
      return NO;
  }
}
NSString *NSStringFromEIM_CMD_TYPE(EIM_CMD_TYPE value) {
  switch (value) {
    case EIM_CMD_TYPEEimCmdAuth:
      return @"EIM_CMD_TYPEEimCmdAuth";
    case EIM_CMD_TYPEEimCmdHeartbeat:
      return @"EIM_CMD_TYPEEimCmdHeartbeat";
    case EIM_CMD_TYPEEimCmdMessage:
      return @"EIM_CMD_TYPEEimCmdMessage";
    case EIM_CMD_TYPEEimCmdGroupMessage:
      return @"EIM_CMD_TYPEEimCmdGroupMessage";
    case EIM_CMD_TYPEEimCmdPullMessage:
      return @"EIM_CMD_TYPEEimCmdPullMessage";
    case EIM_CMD_TYPEDeviceReconnectionAuth:
      return @"EIM_CMD_TYPEDeviceReconnectionAuth";
    case EIM_CMD_TYPEEimUserMsgNotification:
      return @"EIM_CMD_TYPEEimUserMsgNotification";
    case EIM_CMD_TYPEEimUserAddBlackList:
      return @"EIM_CMD_TYPEEimUserAddBlackList";
    case EIM_CMD_TYPEEimCreateGroup:
      return @"EIM_CMD_TYPEEimCreateGroup";
    case EIM_CMD_TYPEEimInviteJoinGroup:
      return @"EIM_CMD_TYPEEimInviteJoinGroup";
    case EIM_CMD_TYPEEimRemoveFromGroup:
      return @"EIM_CMD_TYPEEimRemoveFromGroup";
    case EIM_CMD_TYPEEimGroupOwnerTransfer:
      return @"EIM_CMD_TYPEEimGroupOwnerTransfer";
    case EIM_CMD_TYPEEimAddGroupManager:
      return @"EIM_CMD_TYPEEimAddGroupManager";
    case EIM_CMD_TYPEEimAddGroupAnnouncement:
      return @"EIM_CMD_TYPEEimAddGroupAnnouncement";
    case EIM_CMD_TYPEEimSetGroupName:
      return @"EIM_CMD_TYPEEimSetGroupName";
    case EIM_CMD_TYPEEimSetGroupUserNickname:
      return @"EIM_CMD_TYPEEimSetGroupUserNickname";
    case EIM_CMD_TYPEEimQuitGroup:
      return @"EIM_CMD_TYPEEimQuitGroup";
    case EIM_CMD_TYPEEimVoipCreateToken:
      return @"EIM_CMD_TYPEEimVoipCreateToken";
    case EIM_CMD_TYPEEimCreateVoipSolo:
      return @"EIM_CMD_TYPEEimCreateVoipSolo";
    case EIM_CMD_TYPEEimCreateVoipGroup:
      return @"EIM_CMD_TYPEEimCreateVoipGroup";
    case EIM_CMD_TYPEEimJoinVoip:
      return @"EIM_CMD_TYPEEimJoinVoip";
    case EIM_CMD_TYPEEimRefuseVoip:
      return @"EIM_CMD_TYPEEimRefuseVoip";
    case EIM_CMD_TYPEEimCancelVoip:
      return @"EIM_CMD_TYPEEimCancelVoip";
    case EIM_CMD_TYPEEimHangupVoip:
      return @"EIM_CMD_TYPEEimHangupVoip";
    case EIM_CMD_TYPEEimBusyVoip:
      return @"EIM_CMD_TYPEEimBusyVoip";
    case EIM_CMD_TYPEEimAgroaConnectedVoip:
      return @"EIM_CMD_TYPEEimAgroaConnectedVoip";
    case EIM_CMD_TYPEEimVoipBroadcastAck:
      return @"EIM_CMD_TYPEEimVoipBroadcastAck";
    case EIM_CMD_TYPEEimJoinVoipBroadcastAck:
      return @"EIM_CMD_TYPEEimJoinVoipBroadcastAck";
    case EIM_CMD_TYPEEimRefuseVoipBroadcastAck:
      return @"EIM_CMD_TYPEEimRefuseVoipBroadcastAck";
    case EIM_CMD_TYPEEimCancelVoipBroadcastAck:
      return @"EIM_CMD_TYPEEimCancelVoipBroadcastAck";
    case EIM_CMD_TYPEEimHangupVoipBroadcastAck:
      return @"EIM_CMD_TYPEEimHangupVoipBroadcastAck";
    case EIM_CMD_TYPEEimReportRunStatus:
      return @"EIM_CMD_TYPEEimReportRunStatus";
    case EIM_CMD_TYPEEimJoinGroup:
      return @"EIM_CMD_TYPEEimJoinGroup";
    case EIM_CMD_TYPEEimSetGroupNotificaton:
      return @"EIM_CMD_TYPEEimSetGroupNotificaton";
    case EIM_CMD_TYPEEimDeleteGroupManager:
      return @"EIM_CMD_TYPEEimDeleteGroupManager";
    case EIM_CMD_TYPEAuthAck:
      return @"EIM_CMD_TYPEAuthAck";
    case EIM_CMD_TYPEHeaetbeatAck:
      return @"EIM_CMD_TYPEHeaetbeatAck";
    case EIM_CMD_TYPESendMessageAck:
      return @"EIM_CMD_TYPESendMessageAck";
    case EIM_CMD_TYPEPullMessageAck:
      return @"EIM_CMD_TYPEPullMessageAck";
    case EIM_CMD_TYPEPullSequenceAck:
      return @"EIM_CMD_TYPEPullSequenceAck";
    case EIM_CMD_TYPEUserMsgNotificationAck:
      return @"EIM_CMD_TYPEUserMsgNotificationAck";
    case EIM_CMD_TYPEUserAddBlackListAck:
      return @"EIM_CMD_TYPEUserAddBlackListAck";
    case EIM_CMD_TYPEReportRunStatusAck:
      return @"EIM_CMD_TYPEReportRunStatusAck";
    case EIM_CMD_TYPECreateGroupAck:
      return @"EIM_CMD_TYPECreateGroupAck";
    case EIM_CMD_TYPEUpdateGroupRemarkAck:
      return @"EIM_CMD_TYPEUpdateGroupRemarkAck";
    case EIM_CMD_TYPEUpdateGroupNameAck:
      return @"EIM_CMD_TYPEUpdateGroupNameAck";
    case EIM_CMD_TYPEJoinGroupAck:
      return @"EIM_CMD_TYPEJoinGroupAck";
    case EIM_CMD_TYPEUpdateGroupNicknameAck:
      return @"EIM_CMD_TYPEUpdateGroupNicknameAck";
    case EIM_CMD_TYPEQuitGroupAck:
      return @"EIM_CMD_TYPEQuitGroupAck";
    case EIM_CMD_TYPEAddGroupMangerAck:
      return @"EIM_CMD_TYPEAddGroupMangerAck";
    case EIM_CMD_TYPEInviteJoinGroupAck:
      return @"EIM_CMD_TYPEInviteJoinGroupAck";
    case EIM_CMD_TYPERemoveFromGroupAck:
      return @"EIM_CMD_TYPERemoveFromGroupAck";
    case EIM_CMD_TYPEGroupOwnerTransferAck:
      return @"EIM_CMD_TYPEGroupOwnerTransferAck";
    case EIM_CMD_TYPEDeviceReconnectionAuthAck:
      return @"EIM_CMD_TYPEDeviceReconnectionAuthAck";
    case EIM_CMD_TYPESetGroupNotificationAck:
      return @"EIM_CMD_TYPESetGroupNotificationAck";
    case EIM_CMD_TYPEDeleteGroupManagerAck:
      return @"EIM_CMD_TYPEDeleteGroupManagerAck";
    case EIM_CMD_TYPEEimNotifyNewMsgPush:
      return @"EIM_CMD_TYPEEimNotifyNewMsgPush";
    case EIM_CMD_TYPEEimCreateGroupBroadcase:
      return @"EIM_CMD_TYPEEimCreateGroupBroadcase";
    case EIM_CMD_TYPEEimJoinGroupBroadcase:
      return @"EIM_CMD_TYPEEimJoinGroupBroadcase";
    case EIM_CMD_TYPEEimQuitGroupBroadcase:
      return @"EIM_CMD_TYPEEimQuitGroupBroadcase";
    case EIM_CMD_TYPEEimSetManagerGroupBroadcase:
      return @"EIM_CMD_TYPEEimSetManagerGroupBroadcase";
    case EIM_CMD_TYPEEimOwnerTranserBroadcase:
      return @"EIM_CMD_TYPEEimOwnerTranserBroadcase";
    case EIM_CMD_TYPEEimGroupRenameBroadcase:
      return @"EIM_CMD_TYPEEimGroupRenameBroadcase";
    case EIM_CMD_TYPEEimOwnerQuitGroupBroadcase:
      return @"EIM_CMD_TYPEEimOwnerQuitGroupBroadcase";
    case EIM_CMD_TYPEEimDeleteUserGroupBroadcase:
      return @"EIM_CMD_TYPEEimDeleteUserGroupBroadcase";
    case EIM_CMD_TYPEEimSoloVoipBroadcast:
      return @"EIM_CMD_TYPEEimSoloVoipBroadcast";
    case EIM_CMD_TYPEEimGroupVoipBroadcast:
      return @"EIM_CMD_TYPEEimGroupVoipBroadcast";
    case EIM_CMD_TYPEEimUserJoinVoipBroadcast:
      return @"EIM_CMD_TYPEEimUserJoinVoipBroadcast";
    case EIM_CMD_TYPEEimRefuseVoipBroadcast:
      return @"EIM_CMD_TYPEEimRefuseVoipBroadcast";
    case EIM_CMD_TYPEEimCancelVoipBroadcast:
      return @"EIM_CMD_TYPEEimCancelVoipBroadcast";
    case EIM_CMD_TYPEEimHangupVoipBroadcast:
      return @"EIM_CMD_TYPEEimHangupVoipBroadcast";
    case EIM_CMD_TYPEEimBusyToVoipBroadcast:
      return @"EIM_CMD_TYPEEimBusyToVoipBroadcast";
    case EIM_CMD_TYPEEimAgoraConnectedVoipBroadcast:
      return @"EIM_CMD_TYPEEimAgoraConnectedVoipBroadcast";
    case EIM_CMD_TYPEEimOwnerDeleteGroupBroadcast:
      return @"EIM_CMD_TYPEEimOwnerDeleteGroupBroadcast";
    case EIM_CMD_TYPEEimGroupRemarkUpdateBroadcast:
      return @"EIM_CMD_TYPEEimGroupRemarkUpdateBroadcast";
    default:
      return nil;
  }
}

BOOL EIM_RET_CODEIsValidValue(EIM_RET_CODE value) {
  switch (value) {
    case EIM_RET_CODERetSuccess:
    case EIM_RET_CODERetInternalErr:
    case EIM_RET_CODERetPbErr:
    case EIM_RET_CODERetTokenInvalid:
    case EIM_RET_CODERetSessionTimeout:
    case EIM_RET_CODERetCmdInvalid:
    case EIM_RET_CODERetWnsUidMiss:
    case EIM_RET_CODERetInputParamErr:
    case EIM_RET_CODERetGroupNotExists:
    case EIM_RET_CODERetInBlackList:
    case EIM_RET_CODERetNotInGroup:
    case EIM_RET_CODERetNotGroupManager:
    case EIM_RET_CODERetCanNotDeleteGroupOwner:
    case EIM_RET_CODERetNotGroupOwner:
      return YES;
    default:
      return NO;
  }
}
NSString *NSStringFromEIM_RET_CODE(EIM_RET_CODE value) {
  switch (value) {
    case EIM_RET_CODERetSuccess:
      return @"EIM_RET_CODERetSuccess";
    case EIM_RET_CODERetInternalErr:
      return @"EIM_RET_CODERetInternalErr";
    case EIM_RET_CODERetPbErr:
      return @"EIM_RET_CODERetPbErr";
    case EIM_RET_CODERetTokenInvalid:
      return @"EIM_RET_CODERetTokenInvalid";
    case EIM_RET_CODERetSessionTimeout:
      return @"EIM_RET_CODERetSessionTimeout";
    case EIM_RET_CODERetCmdInvalid:
      return @"EIM_RET_CODERetCmdInvalid";
    case EIM_RET_CODERetWnsUidMiss:
      return @"EIM_RET_CODERetWnsUidMiss";
    case EIM_RET_CODERetInputParamErr:
      return @"EIM_RET_CODERetInputParamErr";
    case EIM_RET_CODERetGroupNotExists:
      return @"EIM_RET_CODERetGroupNotExists";
    case EIM_RET_CODERetInBlackList:
      return @"EIM_RET_CODERetInBlackList";
    case EIM_RET_CODERetNotInGroup:
      return @"EIM_RET_CODERetNotInGroup";
    case EIM_RET_CODERetNotGroupManager:
      return @"EIM_RET_CODERetNotGroupManager";
    case EIM_RET_CODERetCanNotDeleteGroupOwner:
      return @"EIM_RET_CODERetCanNotDeleteGroupOwner";
    case EIM_RET_CODERetNotGroupOwner:
      return @"EIM_RET_CODERetNotGroupOwner";
    default:
      return nil;
  }
}


// @@protoc_insertion_point(global_scope)
