// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Eim_message.pb.h"
#import "Eim_user.pb.h"
// @@protoc_insertion_point(imports)

@class AccountInfo;
@class AccountInfoBuilder;
@class AuthReq;
@class AuthReqBuilder;
@class AuthResp;
@class AuthRespBuilder;
@class BusyVoIPReq;
@class BusyVoIPReqBuilder;
@class BusyVoIPResp;
@class BusyVoIPRespBuilder;
@class CancelVoIPReq;
@class CancelVoIPReqBuilder;
@class CancelVoIPResp;
@class CancelVoIPRespBuilder;
@class ConnectedAgoraVoIPReq;
@class ConnectedAgoraVoIPReqBuilder;
@class ConnectedAgoraVoIPResp;
@class ConnectedAgoraVoIPRespBuilder;
@class CreateBlackReq;
@class CreateBlackReqBuilder;
@class CreateBlackResp;
@class CreateBlackRespBuilder;
@class CreateGroupReq;
@class CreateGroupReqBuilder;
@class CreateGroupResp;
@class CreateGroupRespBuilder;
@class CreateGroupVoIPReq;
@class CreateGroupVoIPReqBuilder;
@class CreateGroupVoIPResp;
@class CreateGroupVoIPRespBuilder;
@class CreateNotificationReq;
@class CreateNotificationReqBuilder;
@class CreateNotificationResp;
@class CreateNotificationRespBuilder;
@class CreateSoloVoIPReq;
@class CreateSoloVoIPReqBuilder;
@class CreateSoloVoIPResp;
@class CreateSoloVoIPRespBuilder;
@class CreateVoIPTokenReq;
@class CreateVoIPTokenReqBuilder;
@class CreateVoIPTokenResp;
@class CreateVoIPTokenRespBuilder;
@class EIMRespHeader;
@class EIMRespHeaderBuilder;
@class GroupMessageReq;
@class GroupMessageReqBuilder;
@class HangupVoIPReq;
@class HangupVoIPReqBuilder;
@class HangupVoIPResp;
@class HangupVoIPRespBuilder;
@class HearBeatReq;
@class HearBeatReqBuilder;
@class HearBeatResp;
@class HearBeatRespBuilder;
@class InvitedJoinGroupReq;
@class InvitedJoinGroupReqBuilder;
@class InvitedJoinGroupResp;
@class InvitedJoinGroupRespBuilder;
@class JoinGroupReq;
@class JoinGroupReqBuilder;
@class JoinGroupResp;
@class JoinGroupRespBuilder;
@class JoinVoIPReq;
@class JoinVoIPReqBuilder;
@class JoinVoIPResp;
@class JoinVoIPRespBuilder;
@class MessageReq;
@class MessageReqBuilder;
@class MessageResp;
@class MessageRespBuilder;
@class PullMessageReq;
@class PullMessageReqBuilder;
@class PullMessageResp;
@class PullMessageRespBuilder;
@class QuitGroupReq;
@class QuitGroupReqBuilder;
@class QuitGroupResp;
@class QuitGroupRespBuilder;
@class ReceivedCancelVoIPBroadcastAckReq;
@class ReceivedCancelVoIPBroadcastAckReqBuilder;
@class ReceivedCancelVoIPBroadcastAckResp;
@class ReceivedCancelVoIPBroadcastAckRespBuilder;
@class ReceivedHangupVoIPBroadcastAckReq;
@class ReceivedHangupVoIPBroadcastAckReqBuilder;
@class ReceivedHangupVoIPBroadcastAckResp;
@class ReceivedHangupVoIPBroadcastAckRespBuilder;
@class ReceivedJoinVoIPBroadcastAckReq;
@class ReceivedJoinVoIPBroadcastAckReqBuilder;
@class ReceivedJoinVoIPBroadcastAckResp;
@class ReceivedJoinVoIPBroadcastAckRespBuilder;
@class ReceivedRefusedVoIPBroadcastAckReq;
@class ReceivedRefusedVoIPBroadcastAckReqBuilder;
@class ReceivedRefusedVoIPBroadcastAckResp;
@class ReceivedRefusedVoIPBroadcastAckRespBuilder;
@class ReceivedVoIPAckReq;
@class ReceivedVoIPAckReqBuilder;
@class ReceivedVoIPAckResp;
@class ReceivedVoIPAckRespBuilder;
@class RefuseVoIPReq;
@class RefuseVoIPReqBuilder;
@class RefuseVoIPResp;
@class RefuseVoIPRespBuilder;
@class RemoveMemberReq;
@class RemoveMemberReqBuilder;
@class RemoveMemberResp;
@class RemoveMemberRespBuilder;
@class ReportRunStatusReq;
@class ReportRunStatusReqBuilder;
@class ReportRunStatusResp;
@class ReportRunStatusRespBuilder;
@class SendMessageResp;
@class SendMessageRespBuilder;
@class SetGroupAnnouncementReq;
@class SetGroupAnnouncementReqBuilder;
@class SetGroupAnnouncementResp;
@class SetGroupAnnouncementRespBuilder;
@class SetGroupNameReq;
@class SetGroupNameReqBuilder;
@class SetGroupNameResp;
@class SetGroupNameRespBuilder;
@class SetGroupUserNickNameReq;
@class SetGroupUserNickNameReqBuilder;
@class SetGroupUserNickNameResp;
@class SetGroupUserNickNameRespBuilder;
@class SetManagerReq;
@class SetManagerReqBuilder;
@class SetManagerResp;
@class SetManagerRespBuilder;
@class TransferGroupOwnerReq;
@class TransferGroupOwnerReqBuilder;
@class TransferGroupOwnerResp;
@class TransferGroupOwnerRespBuilder;



@interface EimVoipRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define CreateVoIPTokenReq_channel_name @"channelName"
#define CreateVoIPTokenReq_voip_type @"voipType"
@interface CreateVoIPTokenReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasVoipType_:1;
  NSString* channelName;
  NSString* voipType;
}
- (BOOL) hasChannelName;
- (BOOL) hasVoipType;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) NSString* voipType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateVoIPTokenReqBuilder*) builder;
+ (CreateVoIPTokenReqBuilder*) builder;
+ (CreateVoIPTokenReqBuilder*) builderWithPrototype:(CreateVoIPTokenReq*) prototype;
- (CreateVoIPTokenReqBuilder*) toBuilder;

+ (CreateVoIPTokenReq*) parseFromData:(NSData*) data;
+ (CreateVoIPTokenReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateVoIPTokenReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateVoIPTokenReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateVoIPTokenReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateVoIPTokenReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateVoIPTokenReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateVoIPTokenReq* resultCreateVoIptokenReq;
}

- (CreateVoIPTokenReq*) defaultInstance;

- (CreateVoIPTokenReqBuilder*) clear;
- (CreateVoIPTokenReqBuilder*) clone;

- (CreateVoIPTokenReq*) build;
- (CreateVoIPTokenReq*) buildPartial;

- (CreateVoIPTokenReqBuilder*) mergeFrom:(CreateVoIPTokenReq*) other;
- (CreateVoIPTokenReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateVoIPTokenReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (CreateVoIPTokenReqBuilder*) setChannelName:(NSString*) value;
- (CreateVoIPTokenReqBuilder*) clearChannelName;

- (BOOL) hasVoipType;
- (NSString*) voipType;
- (CreateVoIPTokenReqBuilder*) setVoipType:(NSString*) value;
- (CreateVoIPTokenReqBuilder*) clearVoipType;
@end

#define CreateVoIPTokenResp_status @"status"
#define CreateVoIPTokenResp_channel_name @"channelName"
#define CreateVoIPTokenResp_token @"token"
#define CreateVoIPTokenResp_expireTimestamp @"expireTimestamp"
@interface CreateVoIPTokenResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasExpireTimestamp_:1;
  BOOL hasChannelName_:1;
  BOOL hasToken_:1;
  BOOL hasStatus_:1;
  SInt64 expireTimestamp;
  NSString* channelName;
  NSString* token;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasChannelName;
- (BOOL) hasToken;
- (BOOL) hasExpireTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) NSString* token;
@property (readonly) SInt64 expireTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateVoIPTokenRespBuilder*) builder;
+ (CreateVoIPTokenRespBuilder*) builder;
+ (CreateVoIPTokenRespBuilder*) builderWithPrototype:(CreateVoIPTokenResp*) prototype;
- (CreateVoIPTokenRespBuilder*) toBuilder;

+ (CreateVoIPTokenResp*) parseFromData:(NSData*) data;
+ (CreateVoIPTokenResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateVoIPTokenResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateVoIPTokenResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateVoIPTokenResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateVoIPTokenResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateVoIPTokenRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateVoIPTokenResp* resultCreateVoIptokenResp;
}

- (CreateVoIPTokenResp*) defaultInstance;

- (CreateVoIPTokenRespBuilder*) clear;
- (CreateVoIPTokenRespBuilder*) clone;

- (CreateVoIPTokenResp*) build;
- (CreateVoIPTokenResp*) buildPartial;

- (CreateVoIPTokenRespBuilder*) mergeFrom:(CreateVoIPTokenResp*) other;
- (CreateVoIPTokenRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateVoIPTokenRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateVoIPTokenRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateVoIPTokenRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateVoIPTokenRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateVoIPTokenRespBuilder*) clearStatus;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (CreateVoIPTokenRespBuilder*) setChannelName:(NSString*) value;
- (CreateVoIPTokenRespBuilder*) clearChannelName;

- (BOOL) hasToken;
- (NSString*) token;
- (CreateVoIPTokenRespBuilder*) setToken:(NSString*) value;
- (CreateVoIPTokenRespBuilder*) clearToken;

- (BOOL) hasExpireTimestamp;
- (SInt64) expireTimestamp;
- (CreateVoIPTokenRespBuilder*) setExpireTimestamp:(SInt64) value;
- (CreateVoIPTokenRespBuilder*) clearExpireTimestamp;
@end

#define CreateSoloVoIPReq_channel_name @"channelName"
#define CreateSoloVoIPReq_voip_type @"voipType"
#define CreateSoloVoIPReq_invitee_id @"inviteeId"
#define CreateSoloVoIPReq_member @"member"
@interface CreateSoloVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInviteeId_:1;
  BOOL hasChannelName_:1;
  BOOL hasVoipType_:1;
  BOOL hasMember_:1;
  SInt64 inviteeId;
  NSString* channelName;
  NSString* voipType;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasVoipType;
- (BOOL) hasInviteeId;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) NSString* voipType;
@property (readonly) SInt64 inviteeId;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateSoloVoIPReqBuilder*) builder;
+ (CreateSoloVoIPReqBuilder*) builder;
+ (CreateSoloVoIPReqBuilder*) builderWithPrototype:(CreateSoloVoIPReq*) prototype;
- (CreateSoloVoIPReqBuilder*) toBuilder;

+ (CreateSoloVoIPReq*) parseFromData:(NSData*) data;
+ (CreateSoloVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateSoloVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateSoloVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateSoloVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateSoloVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateSoloVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateSoloVoIPReq* resultCreateSoloVoIpreq;
}

- (CreateSoloVoIPReq*) defaultInstance;

- (CreateSoloVoIPReqBuilder*) clear;
- (CreateSoloVoIPReqBuilder*) clone;

- (CreateSoloVoIPReq*) build;
- (CreateSoloVoIPReq*) buildPartial;

- (CreateSoloVoIPReqBuilder*) mergeFrom:(CreateSoloVoIPReq*) other;
- (CreateSoloVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateSoloVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (CreateSoloVoIPReqBuilder*) setChannelName:(NSString*) value;
- (CreateSoloVoIPReqBuilder*) clearChannelName;

- (BOOL) hasVoipType;
- (NSString*) voipType;
- (CreateSoloVoIPReqBuilder*) setVoipType:(NSString*) value;
- (CreateSoloVoIPReqBuilder*) clearVoipType;

- (BOOL) hasInviteeId;
- (SInt64) inviteeId;
- (CreateSoloVoIPReqBuilder*) setInviteeId:(SInt64) value;
- (CreateSoloVoIPReqBuilder*) clearInviteeId;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (CreateSoloVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (CreateSoloVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (CreateSoloVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (CreateSoloVoIPReqBuilder*) clearMember;
@end

#define CreateSoloVoIPResp_status @"status"
@interface CreateSoloVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateSoloVoIPRespBuilder*) builder;
+ (CreateSoloVoIPRespBuilder*) builder;
+ (CreateSoloVoIPRespBuilder*) builderWithPrototype:(CreateSoloVoIPResp*) prototype;
- (CreateSoloVoIPRespBuilder*) toBuilder;

+ (CreateSoloVoIPResp*) parseFromData:(NSData*) data;
+ (CreateSoloVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateSoloVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateSoloVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateSoloVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateSoloVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateSoloVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateSoloVoIPResp* resultCreateSoloVoIpresp;
}

- (CreateSoloVoIPResp*) defaultInstance;

- (CreateSoloVoIPRespBuilder*) clear;
- (CreateSoloVoIPRespBuilder*) clone;

- (CreateSoloVoIPResp*) build;
- (CreateSoloVoIPResp*) buildPartial;

- (CreateSoloVoIPRespBuilder*) mergeFrom:(CreateSoloVoIPResp*) other;
- (CreateSoloVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateSoloVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateSoloVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateSoloVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateSoloVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateSoloVoIPRespBuilder*) clearStatus;
@end

#define CreateGroupVoIPReq_channel_name @"channelName"
#define CreateGroupVoIPReq_voip_type @"voipType"
#define CreateGroupVoIPReq_group_id @"groupId"
#define CreateGroupVoIPReq_member @"member"
@interface CreateGroupVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasChannelName_:1;
  BOOL hasVoipType_:1;
  BOOL hasMember_:1;
  SInt64 groupId;
  NSString* channelName;
  NSString* voipType;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasVoipType;
- (BOOL) hasGroupId;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) NSString* voipType;
@property (readonly) SInt64 groupId;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupVoIPReqBuilder*) builder;
+ (CreateGroupVoIPReqBuilder*) builder;
+ (CreateGroupVoIPReqBuilder*) builderWithPrototype:(CreateGroupVoIPReq*) prototype;
- (CreateGroupVoIPReqBuilder*) toBuilder;

+ (CreateGroupVoIPReq*) parseFromData:(NSData*) data;
+ (CreateGroupVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupVoIPReq* resultCreateGroupVoIpreq;
}

- (CreateGroupVoIPReq*) defaultInstance;

- (CreateGroupVoIPReqBuilder*) clear;
- (CreateGroupVoIPReqBuilder*) clone;

- (CreateGroupVoIPReq*) build;
- (CreateGroupVoIPReq*) buildPartial;

- (CreateGroupVoIPReqBuilder*) mergeFrom:(CreateGroupVoIPReq*) other;
- (CreateGroupVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (CreateGroupVoIPReqBuilder*) setChannelName:(NSString*) value;
- (CreateGroupVoIPReqBuilder*) clearChannelName;

- (BOOL) hasVoipType;
- (NSString*) voipType;
- (CreateGroupVoIPReqBuilder*) setVoipType:(NSString*) value;
- (CreateGroupVoIPReqBuilder*) clearVoipType;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (CreateGroupVoIPReqBuilder*) setGroupId:(SInt64) value;
- (CreateGroupVoIPReqBuilder*) clearGroupId;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (CreateGroupVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (CreateGroupVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (CreateGroupVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (CreateGroupVoIPReqBuilder*) clearMember;
@end

#define CreateGroupVoIPResp_status @"status"
@interface CreateGroupVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupVoIPRespBuilder*) builder;
+ (CreateGroupVoIPRespBuilder*) builder;
+ (CreateGroupVoIPRespBuilder*) builderWithPrototype:(CreateGroupVoIPResp*) prototype;
- (CreateGroupVoIPRespBuilder*) toBuilder;

+ (CreateGroupVoIPResp*) parseFromData:(NSData*) data;
+ (CreateGroupVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupVoIPResp* resultCreateGroupVoIpresp;
}

- (CreateGroupVoIPResp*) defaultInstance;

- (CreateGroupVoIPRespBuilder*) clear;
- (CreateGroupVoIPRespBuilder*) clone;

- (CreateGroupVoIPResp*) build;
- (CreateGroupVoIPResp*) buildPartial;

- (CreateGroupVoIPRespBuilder*) mergeFrom:(CreateGroupVoIPResp*) other;
- (CreateGroupVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateGroupVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateGroupVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateGroupVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateGroupVoIPRespBuilder*) clearStatus;
@end

#define JoinVoIPReq_channel_name @"channelName"
#define JoinVoIPReq_member @"member"
@interface JoinVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (JoinVoIPReqBuilder*) builder;
+ (JoinVoIPReqBuilder*) builder;
+ (JoinVoIPReqBuilder*) builderWithPrototype:(JoinVoIPReq*) prototype;
- (JoinVoIPReqBuilder*) toBuilder;

+ (JoinVoIPReq*) parseFromData:(NSData*) data;
+ (JoinVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (JoinVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (JoinVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface JoinVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  JoinVoIPReq* resultJoinVoIpreq;
}

- (JoinVoIPReq*) defaultInstance;

- (JoinVoIPReqBuilder*) clear;
- (JoinVoIPReqBuilder*) clone;

- (JoinVoIPReq*) build;
- (JoinVoIPReq*) buildPartial;

- (JoinVoIPReqBuilder*) mergeFrom:(JoinVoIPReq*) other;
- (JoinVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (JoinVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (JoinVoIPReqBuilder*) setChannelName:(NSString*) value;
- (JoinVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (JoinVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (JoinVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (JoinVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (JoinVoIPReqBuilder*) clearMember;
@end

#define JoinVoIPResp_status @"status"
@interface JoinVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (JoinVoIPRespBuilder*) builder;
+ (JoinVoIPRespBuilder*) builder;
+ (JoinVoIPRespBuilder*) builderWithPrototype:(JoinVoIPResp*) prototype;
- (JoinVoIPRespBuilder*) toBuilder;

+ (JoinVoIPResp*) parseFromData:(NSData*) data;
+ (JoinVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (JoinVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (JoinVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface JoinVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  JoinVoIPResp* resultJoinVoIpresp;
}

- (JoinVoIPResp*) defaultInstance;

- (JoinVoIPRespBuilder*) clear;
- (JoinVoIPRespBuilder*) clone;

- (JoinVoIPResp*) build;
- (JoinVoIPResp*) buildPartial;

- (JoinVoIPRespBuilder*) mergeFrom:(JoinVoIPResp*) other;
- (JoinVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (JoinVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (JoinVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (JoinVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (JoinVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (JoinVoIPRespBuilder*) clearStatus;
@end

#define RefuseVoIPReq_channel_name @"channelName"
#define RefuseVoIPReq_member @"member"
@interface RefuseVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefuseVoIPReqBuilder*) builder;
+ (RefuseVoIPReqBuilder*) builder;
+ (RefuseVoIPReqBuilder*) builderWithPrototype:(RefuseVoIPReq*) prototype;
- (RefuseVoIPReqBuilder*) toBuilder;

+ (RefuseVoIPReq*) parseFromData:(NSData*) data;
+ (RefuseVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (RefuseVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefuseVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RefuseVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  RefuseVoIPReq* resultRefuseVoIpreq;
}

- (RefuseVoIPReq*) defaultInstance;

- (RefuseVoIPReqBuilder*) clear;
- (RefuseVoIPReqBuilder*) clone;

- (RefuseVoIPReq*) build;
- (RefuseVoIPReq*) buildPartial;

- (RefuseVoIPReqBuilder*) mergeFrom:(RefuseVoIPReq*) other;
- (RefuseVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefuseVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (RefuseVoIPReqBuilder*) setChannelName:(NSString*) value;
- (RefuseVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (RefuseVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (RefuseVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (RefuseVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (RefuseVoIPReqBuilder*) clearMember;
@end

#define RefuseVoIPResp_status @"status"
@interface RefuseVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefuseVoIPRespBuilder*) builder;
+ (RefuseVoIPRespBuilder*) builder;
+ (RefuseVoIPRespBuilder*) builderWithPrototype:(RefuseVoIPResp*) prototype;
- (RefuseVoIPRespBuilder*) toBuilder;

+ (RefuseVoIPResp*) parseFromData:(NSData*) data;
+ (RefuseVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (RefuseVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefuseVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RefuseVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  RefuseVoIPResp* resultRefuseVoIpresp;
}

- (RefuseVoIPResp*) defaultInstance;

- (RefuseVoIPRespBuilder*) clear;
- (RefuseVoIPRespBuilder*) clone;

- (RefuseVoIPResp*) build;
- (RefuseVoIPResp*) buildPartial;

- (RefuseVoIPRespBuilder*) mergeFrom:(RefuseVoIPResp*) other;
- (RefuseVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefuseVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (RefuseVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (RefuseVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (RefuseVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (RefuseVoIPRespBuilder*) clearStatus;
@end

#define CancelVoIPReq_channel_name @"channelName"
#define CancelVoIPReq_member @"member"
@interface CancelVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CancelVoIPReqBuilder*) builder;
+ (CancelVoIPReqBuilder*) builder;
+ (CancelVoIPReqBuilder*) builderWithPrototype:(CancelVoIPReq*) prototype;
- (CancelVoIPReqBuilder*) toBuilder;

+ (CancelVoIPReq*) parseFromData:(NSData*) data;
+ (CancelVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (CancelVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CancelVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CancelVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  CancelVoIPReq* resultCancelVoIpreq;
}

- (CancelVoIPReq*) defaultInstance;

- (CancelVoIPReqBuilder*) clear;
- (CancelVoIPReqBuilder*) clone;

- (CancelVoIPReq*) build;
- (CancelVoIPReq*) buildPartial;

- (CancelVoIPReqBuilder*) mergeFrom:(CancelVoIPReq*) other;
- (CancelVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CancelVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (CancelVoIPReqBuilder*) setChannelName:(NSString*) value;
- (CancelVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (CancelVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (CancelVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (CancelVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (CancelVoIPReqBuilder*) clearMember;
@end

#define CancelVoIPResp_status @"status"
@interface CancelVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CancelVoIPRespBuilder*) builder;
+ (CancelVoIPRespBuilder*) builder;
+ (CancelVoIPRespBuilder*) builderWithPrototype:(CancelVoIPResp*) prototype;
- (CancelVoIPRespBuilder*) toBuilder;

+ (CancelVoIPResp*) parseFromData:(NSData*) data;
+ (CancelVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (CancelVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CancelVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CancelVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  CancelVoIPResp* resultCancelVoIpresp;
}

- (CancelVoIPResp*) defaultInstance;

- (CancelVoIPRespBuilder*) clear;
- (CancelVoIPRespBuilder*) clone;

- (CancelVoIPResp*) build;
- (CancelVoIPResp*) buildPartial;

- (CancelVoIPRespBuilder*) mergeFrom:(CancelVoIPResp*) other;
- (CancelVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CancelVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CancelVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CancelVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CancelVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CancelVoIPRespBuilder*) clearStatus;
@end

#define HangupVoIPReq_channel_name @"channelName"
#define HangupVoIPReq_member @"member"
@interface HangupVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HangupVoIPReqBuilder*) builder;
+ (HangupVoIPReqBuilder*) builder;
+ (HangupVoIPReqBuilder*) builderWithPrototype:(HangupVoIPReq*) prototype;
- (HangupVoIPReqBuilder*) toBuilder;

+ (HangupVoIPReq*) parseFromData:(NSData*) data;
+ (HangupVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HangupVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (HangupVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HangupVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HangupVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HangupVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  HangupVoIPReq* resultHangupVoIpreq;
}

- (HangupVoIPReq*) defaultInstance;

- (HangupVoIPReqBuilder*) clear;
- (HangupVoIPReqBuilder*) clone;

- (HangupVoIPReq*) build;
- (HangupVoIPReq*) buildPartial;

- (HangupVoIPReqBuilder*) mergeFrom:(HangupVoIPReq*) other;
- (HangupVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HangupVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (HangupVoIPReqBuilder*) setChannelName:(NSString*) value;
- (HangupVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (HangupVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (HangupVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (HangupVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (HangupVoIPReqBuilder*) clearMember;
@end

#define HangupVoIPResp_status @"status"
@interface HangupVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HangupVoIPRespBuilder*) builder;
+ (HangupVoIPRespBuilder*) builder;
+ (HangupVoIPRespBuilder*) builderWithPrototype:(HangupVoIPResp*) prototype;
- (HangupVoIPRespBuilder*) toBuilder;

+ (HangupVoIPResp*) parseFromData:(NSData*) data;
+ (HangupVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HangupVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (HangupVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HangupVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HangupVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HangupVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  HangupVoIPResp* resultHangupVoIpresp;
}

- (HangupVoIPResp*) defaultInstance;

- (HangupVoIPRespBuilder*) clear;
- (HangupVoIPRespBuilder*) clone;

- (HangupVoIPResp*) build;
- (HangupVoIPResp*) buildPartial;

- (HangupVoIPRespBuilder*) mergeFrom:(HangupVoIPResp*) other;
- (HangupVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HangupVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (HangupVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (HangupVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (HangupVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (HangupVoIPRespBuilder*) clearStatus;
@end

#define BusyVoIPReq_channel_name @"channelName"
#define BusyVoIPReq_member @"member"
@interface BusyVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BusyVoIPReqBuilder*) builder;
+ (BusyVoIPReqBuilder*) builder;
+ (BusyVoIPReqBuilder*) builderWithPrototype:(BusyVoIPReq*) prototype;
- (BusyVoIPReqBuilder*) toBuilder;

+ (BusyVoIPReq*) parseFromData:(NSData*) data;
+ (BusyVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BusyVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (BusyVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BusyVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BusyVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BusyVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  BusyVoIPReq* resultBusyVoIpreq;
}

- (BusyVoIPReq*) defaultInstance;

- (BusyVoIPReqBuilder*) clear;
- (BusyVoIPReqBuilder*) clone;

- (BusyVoIPReq*) build;
- (BusyVoIPReq*) buildPartial;

- (BusyVoIPReqBuilder*) mergeFrom:(BusyVoIPReq*) other;
- (BusyVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BusyVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (BusyVoIPReqBuilder*) setChannelName:(NSString*) value;
- (BusyVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (BusyVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (BusyVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (BusyVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (BusyVoIPReqBuilder*) clearMember;
@end

#define BusyVoIPResp_status @"status"
@interface BusyVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BusyVoIPRespBuilder*) builder;
+ (BusyVoIPRespBuilder*) builder;
+ (BusyVoIPRespBuilder*) builderWithPrototype:(BusyVoIPResp*) prototype;
- (BusyVoIPRespBuilder*) toBuilder;

+ (BusyVoIPResp*) parseFromData:(NSData*) data;
+ (BusyVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BusyVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (BusyVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BusyVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BusyVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BusyVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  BusyVoIPResp* resultBusyVoIpresp;
}

- (BusyVoIPResp*) defaultInstance;

- (BusyVoIPRespBuilder*) clear;
- (BusyVoIPRespBuilder*) clone;

- (BusyVoIPResp*) build;
- (BusyVoIPResp*) buildPartial;

- (BusyVoIPRespBuilder*) mergeFrom:(BusyVoIPResp*) other;
- (BusyVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BusyVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (BusyVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (BusyVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (BusyVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (BusyVoIPRespBuilder*) clearStatus;
@end

#define ConnectedAgoraVoIPReq_channel_name @"channelName"
#define ConnectedAgoraVoIPReq_member @"member"
@interface ConnectedAgoraVoIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  BOOL hasMember_:1;
  NSString* channelName;
  AccountInfo* member;
}
- (BOOL) hasChannelName;
- (BOOL) hasMember;
@property (readonly, strong) NSString* channelName;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConnectedAgoraVoIPReqBuilder*) builder;
+ (ConnectedAgoraVoIPReqBuilder*) builder;
+ (ConnectedAgoraVoIPReqBuilder*) builderWithPrototype:(ConnectedAgoraVoIPReq*) prototype;
- (ConnectedAgoraVoIPReqBuilder*) toBuilder;

+ (ConnectedAgoraVoIPReq*) parseFromData:(NSData*) data;
+ (ConnectedAgoraVoIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConnectedAgoraVoIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (ConnectedAgoraVoIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConnectedAgoraVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ConnectedAgoraVoIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConnectedAgoraVoIPReqBuilder : PBGeneratedMessageBuilder {
@private
  ConnectedAgoraVoIPReq* resultConnectedAgoraVoIpreq;
}

- (ConnectedAgoraVoIPReq*) defaultInstance;

- (ConnectedAgoraVoIPReqBuilder*) clear;
- (ConnectedAgoraVoIPReqBuilder*) clone;

- (ConnectedAgoraVoIPReq*) build;
- (ConnectedAgoraVoIPReq*) buildPartial;

- (ConnectedAgoraVoIPReqBuilder*) mergeFrom:(ConnectedAgoraVoIPReq*) other;
- (ConnectedAgoraVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConnectedAgoraVoIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ConnectedAgoraVoIPReqBuilder*) setChannelName:(NSString*) value;
- (ConnectedAgoraVoIPReqBuilder*) clearChannelName;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (ConnectedAgoraVoIPReqBuilder*) setMember:(AccountInfo*) value;
- (ConnectedAgoraVoIPReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (ConnectedAgoraVoIPReqBuilder*) mergeMember:(AccountInfo*) value;
- (ConnectedAgoraVoIPReqBuilder*) clearMember;
@end

#define ConnectedAgoraVoIPResp_status @"status"
@interface ConnectedAgoraVoIPResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConnectedAgoraVoIPRespBuilder*) builder;
+ (ConnectedAgoraVoIPRespBuilder*) builder;
+ (ConnectedAgoraVoIPRespBuilder*) builderWithPrototype:(ConnectedAgoraVoIPResp*) prototype;
- (ConnectedAgoraVoIPRespBuilder*) toBuilder;

+ (ConnectedAgoraVoIPResp*) parseFromData:(NSData*) data;
+ (ConnectedAgoraVoIPResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConnectedAgoraVoIPResp*) parseFromInputStream:(NSInputStream*) input;
+ (ConnectedAgoraVoIPResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConnectedAgoraVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ConnectedAgoraVoIPResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConnectedAgoraVoIPRespBuilder : PBGeneratedMessageBuilder {
@private
  ConnectedAgoraVoIPResp* resultConnectedAgoraVoIpresp;
}

- (ConnectedAgoraVoIPResp*) defaultInstance;

- (ConnectedAgoraVoIPRespBuilder*) clear;
- (ConnectedAgoraVoIPRespBuilder*) clone;

- (ConnectedAgoraVoIPResp*) build;
- (ConnectedAgoraVoIPResp*) buildPartial;

- (ConnectedAgoraVoIPRespBuilder*) mergeFrom:(ConnectedAgoraVoIPResp*) other;
- (ConnectedAgoraVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConnectedAgoraVoIPRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ConnectedAgoraVoIPRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ConnectedAgoraVoIPRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ConnectedAgoraVoIPRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ConnectedAgoraVoIPRespBuilder*) clearStatus;
@end

#define ReceivedVoIPAckReq_channel_name @"channelName"
@interface ReceivedVoIPAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  NSString* channelName;
}
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedVoIPAckReqBuilder*) builder;
+ (ReceivedVoIPAckReqBuilder*) builder;
+ (ReceivedVoIPAckReqBuilder*) builderWithPrototype:(ReceivedVoIPAckReq*) prototype;
- (ReceivedVoIPAckReqBuilder*) toBuilder;

+ (ReceivedVoIPAckReq*) parseFromData:(NSData*) data;
+ (ReceivedVoIPAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedVoIPAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedVoIPAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedVoIPAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedVoIPAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedVoIPAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedVoIPAckReq* resultReceivedVoIpackReq;
}

- (ReceivedVoIPAckReq*) defaultInstance;

- (ReceivedVoIPAckReqBuilder*) clear;
- (ReceivedVoIPAckReqBuilder*) clone;

- (ReceivedVoIPAckReq*) build;
- (ReceivedVoIPAckReq*) buildPartial;

- (ReceivedVoIPAckReqBuilder*) mergeFrom:(ReceivedVoIPAckReq*) other;
- (ReceivedVoIPAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedVoIPAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ReceivedVoIPAckReqBuilder*) setChannelName:(NSString*) value;
- (ReceivedVoIPAckReqBuilder*) clearChannelName;
@end

#define ReceivedVoIPAckResp_status @"status"
@interface ReceivedVoIPAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedVoIPAckRespBuilder*) builder;
+ (ReceivedVoIPAckRespBuilder*) builder;
+ (ReceivedVoIPAckRespBuilder*) builderWithPrototype:(ReceivedVoIPAckResp*) prototype;
- (ReceivedVoIPAckRespBuilder*) toBuilder;

+ (ReceivedVoIPAckResp*) parseFromData:(NSData*) data;
+ (ReceivedVoIPAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedVoIPAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedVoIPAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedVoIPAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedVoIPAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedVoIPAckRespBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedVoIPAckResp* resultReceivedVoIpackResp;
}

- (ReceivedVoIPAckResp*) defaultInstance;

- (ReceivedVoIPAckRespBuilder*) clear;
- (ReceivedVoIPAckRespBuilder*) clone;

- (ReceivedVoIPAckResp*) build;
- (ReceivedVoIPAckResp*) buildPartial;

- (ReceivedVoIPAckRespBuilder*) mergeFrom:(ReceivedVoIPAckResp*) other;
- (ReceivedVoIPAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedVoIPAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReceivedVoIPAckRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReceivedVoIPAckRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReceivedVoIPAckRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReceivedVoIPAckRespBuilder*) clearStatus;
@end

#define ReceivedJoinVoIPBroadcastAckReq_channel_name @"channelName"
@interface ReceivedJoinVoIPBroadcastAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  NSString* channelName;
}
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedJoinVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedJoinVoIPBroadcastAckReqBuilder*) builderWithPrototype:(ReceivedJoinVoIPBroadcastAckReq*) prototype;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) toBuilder;

+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromData:(NSData*) data;
+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedJoinVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedJoinVoIPBroadcastAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedJoinVoIPBroadcastAckReq* resultReceivedJoinVoIpbroadcastAckReq;
}

- (ReceivedJoinVoIPBroadcastAckReq*) defaultInstance;

- (ReceivedJoinVoIPBroadcastAckReqBuilder*) clear;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) clone;

- (ReceivedJoinVoIPBroadcastAckReq*) build;
- (ReceivedJoinVoIPBroadcastAckReq*) buildPartial;

- (ReceivedJoinVoIPBroadcastAckReqBuilder*) mergeFrom:(ReceivedJoinVoIPBroadcastAckReq*) other;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) setChannelName:(NSString*) value;
- (ReceivedJoinVoIPBroadcastAckReqBuilder*) clearChannelName;
@end

#define ReceivedJoinVoIPBroadcastAckResp_status @"status"
@interface ReceivedJoinVoIPBroadcastAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedJoinVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedJoinVoIPBroadcastAckRespBuilder*) builderWithPrototype:(ReceivedJoinVoIPBroadcastAckResp*) prototype;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) toBuilder;

+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromData:(NSData*) data;
+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedJoinVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedJoinVoIPBroadcastAckRespBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedJoinVoIPBroadcastAckResp* resultReceivedJoinVoIpbroadcastAckResp;
}

- (ReceivedJoinVoIPBroadcastAckResp*) defaultInstance;

- (ReceivedJoinVoIPBroadcastAckRespBuilder*) clear;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) clone;

- (ReceivedJoinVoIPBroadcastAckResp*) build;
- (ReceivedJoinVoIPBroadcastAckResp*) buildPartial;

- (ReceivedJoinVoIPBroadcastAckRespBuilder*) mergeFrom:(ReceivedJoinVoIPBroadcastAckResp*) other;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReceivedJoinVoIPBroadcastAckRespBuilder*) clearStatus;
@end

#define ReceivedCancelVoIPBroadcastAckReq_channel_name @"channelName"
@interface ReceivedCancelVoIPBroadcastAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  NSString* channelName;
}
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedCancelVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedCancelVoIPBroadcastAckReqBuilder*) builderWithPrototype:(ReceivedCancelVoIPBroadcastAckReq*) prototype;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) toBuilder;

+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromData:(NSData*) data;
+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedCancelVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedCancelVoIPBroadcastAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedCancelVoIPBroadcastAckReq* resultReceivedCancelVoIpbroadcastAckReq;
}

- (ReceivedCancelVoIPBroadcastAckReq*) defaultInstance;

- (ReceivedCancelVoIPBroadcastAckReqBuilder*) clear;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) clone;

- (ReceivedCancelVoIPBroadcastAckReq*) build;
- (ReceivedCancelVoIPBroadcastAckReq*) buildPartial;

- (ReceivedCancelVoIPBroadcastAckReqBuilder*) mergeFrom:(ReceivedCancelVoIPBroadcastAckReq*) other;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) setChannelName:(NSString*) value;
- (ReceivedCancelVoIPBroadcastAckReqBuilder*) clearChannelName;
@end

#define ReceivedCancelVoIPBroadcastAckResp_status @"status"
@interface ReceivedCancelVoIPBroadcastAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedCancelVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedCancelVoIPBroadcastAckRespBuilder*) builderWithPrototype:(ReceivedCancelVoIPBroadcastAckResp*) prototype;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) toBuilder;

+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromData:(NSData*) data;
+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedCancelVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedCancelVoIPBroadcastAckRespBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedCancelVoIPBroadcastAckResp* resultReceivedCancelVoIpbroadcastAckResp;
}

- (ReceivedCancelVoIPBroadcastAckResp*) defaultInstance;

- (ReceivedCancelVoIPBroadcastAckRespBuilder*) clear;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) clone;

- (ReceivedCancelVoIPBroadcastAckResp*) build;
- (ReceivedCancelVoIPBroadcastAckResp*) buildPartial;

- (ReceivedCancelVoIPBroadcastAckRespBuilder*) mergeFrom:(ReceivedCancelVoIPBroadcastAckResp*) other;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReceivedCancelVoIPBroadcastAckRespBuilder*) clearStatus;
@end

#define ReceivedRefusedVoIPBroadcastAckReq_channel_name @"channelName"
@interface ReceivedRefusedVoIPBroadcastAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  NSString* channelName;
}
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedRefusedVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedRefusedVoIPBroadcastAckReqBuilder*) builderWithPrototype:(ReceivedRefusedVoIPBroadcastAckReq*) prototype;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) toBuilder;

+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromData:(NSData*) data;
+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedRefusedVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedRefusedVoIPBroadcastAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedRefusedVoIPBroadcastAckReq* resultReceivedRefusedVoIpbroadcastAckReq;
}

- (ReceivedRefusedVoIPBroadcastAckReq*) defaultInstance;

- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) clear;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) clone;

- (ReceivedRefusedVoIPBroadcastAckReq*) build;
- (ReceivedRefusedVoIPBroadcastAckReq*) buildPartial;

- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) mergeFrom:(ReceivedRefusedVoIPBroadcastAckReq*) other;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) setChannelName:(NSString*) value;
- (ReceivedRefusedVoIPBroadcastAckReqBuilder*) clearChannelName;
@end

#define ReceivedRefusedVoIPBroadcastAckResp_status @"status"
@interface ReceivedRefusedVoIPBroadcastAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedRefusedVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedRefusedVoIPBroadcastAckRespBuilder*) builderWithPrototype:(ReceivedRefusedVoIPBroadcastAckResp*) prototype;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) toBuilder;

+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromData:(NSData*) data;
+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedRefusedVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedRefusedVoIPBroadcastAckRespBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedRefusedVoIPBroadcastAckResp* resultReceivedRefusedVoIpbroadcastAckResp;
}

- (ReceivedRefusedVoIPBroadcastAckResp*) defaultInstance;

- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) clear;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) clone;

- (ReceivedRefusedVoIPBroadcastAckResp*) build;
- (ReceivedRefusedVoIPBroadcastAckResp*) buildPartial;

- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) mergeFrom:(ReceivedRefusedVoIPBroadcastAckResp*) other;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReceivedRefusedVoIPBroadcastAckRespBuilder*) clearStatus;
@end

#define ReceivedHangupVoIPBroadcastAckReq_channel_name @"channelName"
@interface ReceivedHangupVoIPBroadcastAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChannelName_:1;
  NSString* channelName;
}
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedHangupVoIPBroadcastAckReqBuilder*) builder;
+ (ReceivedHangupVoIPBroadcastAckReqBuilder*) builderWithPrototype:(ReceivedHangupVoIPBroadcastAckReq*) prototype;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) toBuilder;

+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromData:(NSData*) data;
+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedHangupVoIPBroadcastAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedHangupVoIPBroadcastAckReqBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedHangupVoIPBroadcastAckReq* resultReceivedHangupVoIpbroadcastAckReq;
}

- (ReceivedHangupVoIPBroadcastAckReq*) defaultInstance;

- (ReceivedHangupVoIPBroadcastAckReqBuilder*) clear;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) clone;

- (ReceivedHangupVoIPBroadcastAckReq*) build;
- (ReceivedHangupVoIPBroadcastAckReq*) buildPartial;

- (ReceivedHangupVoIPBroadcastAckReqBuilder*) mergeFrom:(ReceivedHangupVoIPBroadcastAckReq*) other;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) setChannelName:(NSString*) value;
- (ReceivedHangupVoIPBroadcastAckReqBuilder*) clearChannelName;
@end

#define ReceivedHangupVoIPBroadcastAckResp_status @"status"
@interface ReceivedHangupVoIPBroadcastAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedHangupVoIPBroadcastAckRespBuilder*) builder;
+ (ReceivedHangupVoIPBroadcastAckRespBuilder*) builderWithPrototype:(ReceivedHangupVoIPBroadcastAckResp*) prototype;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) toBuilder;

+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromData:(NSData*) data;
+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReceivedHangupVoIPBroadcastAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReceivedHangupVoIPBroadcastAckRespBuilder : PBGeneratedMessageBuilder {
@private
  ReceivedHangupVoIPBroadcastAckResp* resultReceivedHangupVoIpbroadcastAckResp;
}

- (ReceivedHangupVoIPBroadcastAckResp*) defaultInstance;

- (ReceivedHangupVoIPBroadcastAckRespBuilder*) clear;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) clone;

- (ReceivedHangupVoIPBroadcastAckResp*) build;
- (ReceivedHangupVoIPBroadcastAckResp*) buildPartial;

- (ReceivedHangupVoIPBroadcastAckRespBuilder*) mergeFrom:(ReceivedHangupVoIPBroadcastAckResp*) other;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReceivedHangupVoIPBroadcastAckRespBuilder*) clearStatus;
@end


// @@protoc_insertion_point(global_scope)
