// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Eim_base.pb.h"
// @@protoc_insertion_point(imports)

@implementation EimBaseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EimBaseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [EimMessageRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface BaseResultResp ()
@property (strong) EIMRespHeader* status;
@end

@implementation BaseResultResp

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) _value_ {
  hasStatus_ = !!_value_;
}
@synthesize status;
- (instancetype) init {
  if ((self = [super init])) {
    self.status = [EIMRespHeader defaultInstance];
  }
  return self;
}
static BaseResultResp* defaultBaseResultRespInstance = nil;
+ (void) initialize {
  if (self == [BaseResultResp class]) {
    defaultBaseResultRespInstance = [[BaseResultResp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultBaseResultRespInstance;
}
- (instancetype) defaultInstance {
  return defaultBaseResultRespInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeMessage:1 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStatus) {
    size_ += computeMessageSize(1, self.status);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (BaseResultResp*) parseFromData:(NSData*) data {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromData:data] build];
}
+ (BaseResultResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BaseResultResp*) parseFromInputStream:(NSInputStream*) input {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromInputStream:input] build];
}
+ (BaseResultResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BaseResultResp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromCodedInputStream:input] build];
}
+ (BaseResultResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BaseResultResp*)[[[BaseResultResp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BaseResultRespBuilder*) builder {
  return [[BaseResultRespBuilder alloc] init];
}
+ (BaseResultRespBuilder*) builderWithPrototype:(BaseResultResp*) prototype {
  return [[BaseResultResp builder] mergeFrom:prototype];
}
- (BaseResultRespBuilder*) builder {
  return [BaseResultResp builder];
}
- (BaseResultRespBuilder*) toBuilder {
  return [BaseResultResp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStatus) {
    [output appendFormat:@"%@%@ {\n", indent, @"status"];
    [self.status writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStatus) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.status storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"status"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[BaseResultResp class]]) {
    return NO;
  }
  BaseResultResp *otherMessage = other;
  return
      self.hasStatus == otherMessage.hasStatus &&
      (!self.hasStatus || [self.status isEqual:otherMessage.status]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStatus) {
    hashCode = hashCode * 31 + [self.status hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface BaseResultRespBuilder()
@property (strong) BaseResultResp* resultBaseResultResp;
@end

@implementation BaseResultRespBuilder
@synthesize resultBaseResultResp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultBaseResultResp = [[BaseResultResp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultBaseResultResp;
}
- (BaseResultRespBuilder*) clear {
  self.resultBaseResultResp = [[BaseResultResp alloc] init];
  return self;
}
- (BaseResultRespBuilder*) clone {
  return [BaseResultResp builderWithPrototype:resultBaseResultResp];
}
- (BaseResultResp*) defaultInstance {
  return [BaseResultResp defaultInstance];
}
- (BaseResultResp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BaseResultResp*) buildPartial {
  BaseResultResp* returnMe = resultBaseResultResp;
  self.resultBaseResultResp = nil;
  return returnMe;
}
- (BaseResultRespBuilder*) mergeFrom:(BaseResultResp*) other {
  if (other == [BaseResultResp defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self mergeStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BaseResultRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BaseResultRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        EIMRespHeaderBuilder* subBuilder = [EIMRespHeader builder];
        if (self.hasStatus) {
          [subBuilder mergeFrom:self.status];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setStatus:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return resultBaseResultResp.hasStatus;
}
- (EIMRespHeader*) status {
  return resultBaseResultResp.status;
}
- (BaseResultRespBuilder*) setStatus:(EIMRespHeader*) value {
  resultBaseResultResp.hasStatus = YES;
  resultBaseResultResp.status = value;
  return self;
}
- (BaseResultRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue {
  return [self setStatus:[builderForValue build]];
}
- (BaseResultRespBuilder*) mergeStatus:(EIMRespHeader*) value {
  if (resultBaseResultResp.hasStatus &&
      resultBaseResultResp.status != [EIMRespHeader defaultInstance]) {
    resultBaseResultResp.status =
      [[[EIMRespHeader builderWithPrototype:resultBaseResultResp.status] mergeFrom:value] buildPartial];
  } else {
    resultBaseResultResp.status = value;
  }
  resultBaseResultResp.hasStatus = YES;
  return self;
}
- (BaseResultRespBuilder*) clearStatus {
  resultBaseResultResp.hasStatus = NO;
  resultBaseResultResp.status = [EIMRespHeader defaultInstance];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
