// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Eim_message.pb.h"
// @@protoc_insertion_point(imports)

@class AccountInfo;
@class AccountInfoBuilder;
@class AuthReq;
@class AuthReqBuilder;
@class AuthResp;
@class AuthRespBuilder;
@class CreateBlackReq;
@class CreateBlackReqBuilder;
@class CreateBlackResp;
@class CreateBlackRespBuilder;
@class CreateGroupNotificationReq;
@class CreateGroupNotificationReqBuilder;
@class CreateGroupNotificationResp;
@class CreateGroupNotificationRespBuilder;
@class CreateGroupReq;
@class CreateGroupReqBuilder;
@class CreateGroupResp;
@class CreateGroupRespBuilder;
@class CreateNotificationReq;
@class CreateNotificationReqBuilder;
@class CreateNotificationResp;
@class CreateNotificationRespBuilder;
@class DeleteGroupUserReq;
@class DeleteGroupUserReqBuilder;
@class DeleteGroupUserResp;
@class DeleteGroupUserRespBuilder;
@class DeleteManagerReq;
@class DeleteManagerReqBuilder;
@class DeleteManagerResp;
@class DeleteManagerRespBuilder;
@class DeviceReconnectionReq;
@class DeviceReconnectionReqBuilder;
@class DeviceReconnectionResp;
@class DeviceReconnectionRespBuilder;
@class EIMRespHeader;
@class EIMRespHeaderBuilder;
@class GroupMessageReq;
@class GroupMessageReqBuilder;
@class HeartBeatReq;
@class HeartBeatReqBuilder;
@class HeartBeatResp;
@class HeartBeatRespBuilder;
@class InvitedJoinGroupReq;
@class InvitedJoinGroupReqBuilder;
@class InvitedJoinGroupResp;
@class InvitedJoinGroupRespBuilder;
@class JoinGroupReq;
@class JoinGroupReqBuilder;
@class JoinGroupResp;
@class JoinGroupRespBuilder;
@class MessageReq;
@class MessageReqBuilder;
@class MessageResp;
@class MessageRespBuilder;
@class PullMessageReq;
@class PullMessageReqBuilder;
@class PullMessageResp;
@class PullMessageRespBuilder;
@class QuitGroupReq;
@class QuitGroupReqBuilder;
@class QuitGroupResp;
@class QuitGroupRespBuilder;
@class ReportRunStatusReq;
@class ReportRunStatusReqBuilder;
@class ReportRunStatusResp;
@class ReportRunStatusRespBuilder;
@class SendMessageResp;
@class SendMessageRespBuilder;
@class SetGroupAnnouncementReq;
@class SetGroupAnnouncementReqBuilder;
@class SetGroupAnnouncementResp;
@class SetGroupAnnouncementRespBuilder;
@class SetGroupNameReq;
@class SetGroupNameReqBuilder;
@class SetGroupNameResp;
@class SetGroupNameRespBuilder;
@class SetGroupUserNickNameReq;
@class SetGroupUserNickNameReqBuilder;
@class SetGroupUserNickNameResp;
@class SetGroupUserNickNameRespBuilder;
@class SetManagerReq;
@class SetManagerReqBuilder;
@class SetManagerResp;
@class SetManagerRespBuilder;
@class TransferGroupOwnerReq;
@class TransferGroupOwnerReqBuilder;
@class TransferGroupOwnerResp;
@class TransferGroupOwnerRespBuilder;



@interface EimUserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define CreateNotificationReq_notification @"notification"
#define CreateNotificationReq_friend_id @"friendId"
@interface CreateNotificationReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNotification_:1;
  BOOL hasFriendId_:1;
  BOOL notification_:1;
  SInt64 friendId;
}
- (BOOL) hasNotification;
- (BOOL) hasFriendId;
- (BOOL) notification;
@property (readonly) SInt64 friendId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateNotificationReqBuilder*) builder;
+ (CreateNotificationReqBuilder*) builder;
+ (CreateNotificationReqBuilder*) builderWithPrototype:(CreateNotificationReq*) prototype;
- (CreateNotificationReqBuilder*) toBuilder;

+ (CreateNotificationReq*) parseFromData:(NSData*) data;
+ (CreateNotificationReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateNotificationReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateNotificationReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateNotificationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateNotificationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateNotificationReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateNotificationReq* resultCreateNotificationReq;
}

- (CreateNotificationReq*) defaultInstance;

- (CreateNotificationReqBuilder*) clear;
- (CreateNotificationReqBuilder*) clone;

- (CreateNotificationReq*) build;
- (CreateNotificationReq*) buildPartial;

- (CreateNotificationReqBuilder*) mergeFrom:(CreateNotificationReq*) other;
- (CreateNotificationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateNotificationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNotification;
- (BOOL) notification;
- (CreateNotificationReqBuilder*) setNotification:(BOOL) value;
- (CreateNotificationReqBuilder*) clearNotification;

- (BOOL) hasFriendId;
- (SInt64) friendId;
- (CreateNotificationReqBuilder*) setFriendId:(SInt64) value;
- (CreateNotificationReqBuilder*) clearFriendId;
@end

#define CreateNotificationResp_status @"status"
@interface CreateNotificationResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateNotificationRespBuilder*) builder;
+ (CreateNotificationRespBuilder*) builder;
+ (CreateNotificationRespBuilder*) builderWithPrototype:(CreateNotificationResp*) prototype;
- (CreateNotificationRespBuilder*) toBuilder;

+ (CreateNotificationResp*) parseFromData:(NSData*) data;
+ (CreateNotificationResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateNotificationResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateNotificationResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateNotificationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateNotificationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateNotificationRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateNotificationResp* resultCreateNotificationResp;
}

- (CreateNotificationResp*) defaultInstance;

- (CreateNotificationRespBuilder*) clear;
- (CreateNotificationRespBuilder*) clone;

- (CreateNotificationResp*) build;
- (CreateNotificationResp*) buildPartial;

- (CreateNotificationRespBuilder*) mergeFrom:(CreateNotificationResp*) other;
- (CreateNotificationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateNotificationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateNotificationRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateNotificationRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateNotificationRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateNotificationRespBuilder*) clearStatus;
@end

#define CreateBlackReq_friend_id @"friendId"
#define CreateBlackReq_reason @"reason"
@interface CreateBlackReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFriendId_:1;
  BOOL hasReason_:1;
  SInt64 friendId;
  NSString* reason;
}
- (BOOL) hasFriendId;
- (BOOL) hasReason;
@property (readonly) SInt64 friendId;
@property (readonly, strong) NSString* reason;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateBlackReqBuilder*) builder;
+ (CreateBlackReqBuilder*) builder;
+ (CreateBlackReqBuilder*) builderWithPrototype:(CreateBlackReq*) prototype;
- (CreateBlackReqBuilder*) toBuilder;

+ (CreateBlackReq*) parseFromData:(NSData*) data;
+ (CreateBlackReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateBlackReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateBlackReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateBlackReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateBlackReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateBlackReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateBlackReq* resultCreateBlackReq;
}

- (CreateBlackReq*) defaultInstance;

- (CreateBlackReqBuilder*) clear;
- (CreateBlackReqBuilder*) clone;

- (CreateBlackReq*) build;
- (CreateBlackReq*) buildPartial;

- (CreateBlackReqBuilder*) mergeFrom:(CreateBlackReq*) other;
- (CreateBlackReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateBlackReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFriendId;
- (SInt64) friendId;
- (CreateBlackReqBuilder*) setFriendId:(SInt64) value;
- (CreateBlackReqBuilder*) clearFriendId;

- (BOOL) hasReason;
- (NSString*) reason;
- (CreateBlackReqBuilder*) setReason:(NSString*) value;
- (CreateBlackReqBuilder*) clearReason;
@end

#define CreateBlackResp_status @"status"
@interface CreateBlackResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateBlackRespBuilder*) builder;
+ (CreateBlackRespBuilder*) builder;
+ (CreateBlackRespBuilder*) builderWithPrototype:(CreateBlackResp*) prototype;
- (CreateBlackRespBuilder*) toBuilder;

+ (CreateBlackResp*) parseFromData:(NSData*) data;
+ (CreateBlackResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateBlackResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateBlackResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateBlackResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateBlackResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateBlackRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateBlackResp* resultCreateBlackResp;
}

- (CreateBlackResp*) defaultInstance;

- (CreateBlackRespBuilder*) clear;
- (CreateBlackRespBuilder*) clone;

- (CreateBlackResp*) build;
- (CreateBlackResp*) buildPartial;

- (CreateBlackRespBuilder*) mergeFrom:(CreateBlackResp*) other;
- (CreateBlackRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateBlackRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateBlackRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateBlackRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateBlackRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateBlackRespBuilder*) clearStatus;
@end

#define AccountInfo_account_id @"accountId"
#define AccountInfo_nick_name @"nickName"
#define AccountInfo_photo_url @"photoUrl"
@interface AccountInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAccountId_:1;
  BOOL hasNickName_:1;
  BOOL hasPhotoUrl_:1;
  SInt64 accountId;
  NSString* nickName;
  NSString* photoUrl;
}
- (BOOL) hasAccountId;
- (BOOL) hasNickName;
- (BOOL) hasPhotoUrl;
@property (readonly) SInt64 accountId;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* photoUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AccountInfoBuilder*) builder;
+ (AccountInfoBuilder*) builder;
+ (AccountInfoBuilder*) builderWithPrototype:(AccountInfo*) prototype;
- (AccountInfoBuilder*) toBuilder;

+ (AccountInfo*) parseFromData:(NSData*) data;
+ (AccountInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AccountInfo*) parseFromInputStream:(NSInputStream*) input;
+ (AccountInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AccountInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AccountInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AccountInfoBuilder : PBGeneratedMessageBuilder {
@private
  AccountInfo* resultAccountInfo;
}

- (AccountInfo*) defaultInstance;

- (AccountInfoBuilder*) clear;
- (AccountInfoBuilder*) clone;

- (AccountInfo*) build;
- (AccountInfo*) buildPartial;

- (AccountInfoBuilder*) mergeFrom:(AccountInfo*) other;
- (AccountInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AccountInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAccountId;
- (SInt64) accountId;
- (AccountInfoBuilder*) setAccountId:(SInt64) value;
- (AccountInfoBuilder*) clearAccountId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (AccountInfoBuilder*) setNickName:(NSString*) value;
- (AccountInfoBuilder*) clearNickName;

- (BOOL) hasPhotoUrl;
- (NSString*) photoUrl;
- (AccountInfoBuilder*) setPhotoUrl:(NSString*) value;
- (AccountInfoBuilder*) clearPhotoUrl;
@end

#define CreateGroupReq_name @"name"
#define CreateGroupReq_creator_name @"creatorName"
#define CreateGroupReq_members @"members"
@interface CreateGroupReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasCreatorName_:1;
  NSString* name;
  NSString* creatorName;
  NSMutableArray * membersArray;
}
- (BOOL) hasName;
- (BOOL) hasCreatorName;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* creatorName;
@property (readonly, strong) NSArray<AccountInfo*> * members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupReqBuilder*) builder;
+ (CreateGroupReqBuilder*) builder;
+ (CreateGroupReqBuilder*) builderWithPrototype:(CreateGroupReq*) prototype;
- (CreateGroupReqBuilder*) toBuilder;

+ (CreateGroupReq*) parseFromData:(NSData*) data;
+ (CreateGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupReq* resultCreateGroupReq;
}

- (CreateGroupReq*) defaultInstance;

- (CreateGroupReqBuilder*) clear;
- (CreateGroupReqBuilder*) clone;

- (CreateGroupReq*) build;
- (CreateGroupReq*) buildPartial;

- (CreateGroupReqBuilder*) mergeFrom:(CreateGroupReq*) other;
- (CreateGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (CreateGroupReqBuilder*) setName:(NSString*) value;
- (CreateGroupReqBuilder*) clearName;

- (BOOL) hasCreatorName;
- (NSString*) creatorName;
- (CreateGroupReqBuilder*) setCreatorName:(NSString*) value;
- (CreateGroupReqBuilder*) clearCreatorName;

- (NSMutableArray<AccountInfo*> *)members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;
- (CreateGroupReqBuilder *)addMembers:(AccountInfo*)value;
- (CreateGroupReqBuilder *)setMembersArray:(NSArray<AccountInfo*> *)array;
- (CreateGroupReqBuilder *)clearMembers;
@end

#define CreateGroupResp_status @"status"
#define CreateGroupResp_group_id @"groupId"
#define CreateGroupResp_group_timestamp @"groupTimestamp"
@interface CreateGroupResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  SInt64 groupId;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupId;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) SInt64 groupId;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupRespBuilder*) builder;
+ (CreateGroupRespBuilder*) builder;
+ (CreateGroupRespBuilder*) builderWithPrototype:(CreateGroupResp*) prototype;
- (CreateGroupRespBuilder*) toBuilder;

+ (CreateGroupResp*) parseFromData:(NSData*) data;
+ (CreateGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupResp* resultCreateGroupResp;
}

- (CreateGroupResp*) defaultInstance;

- (CreateGroupRespBuilder*) clear;
- (CreateGroupRespBuilder*) clone;

- (CreateGroupResp*) build;
- (CreateGroupResp*) buildPartial;

- (CreateGroupRespBuilder*) mergeFrom:(CreateGroupResp*) other;
- (CreateGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateGroupRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateGroupRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateGroupRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateGroupRespBuilder*) clearStatus;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (CreateGroupRespBuilder*) setGroupId:(SInt64) value;
- (CreateGroupRespBuilder*) clearGroupId;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (CreateGroupRespBuilder*) setGroupTimestamp:(UInt64) value;
- (CreateGroupRespBuilder*) clearGroupTimestamp;
@end

#define InvitedJoinGroupReq_group_id @"groupId"
#define InvitedJoinGroupReq_name @"name"
#define InvitedJoinGroupReq_members @"members"
@interface InvitedJoinGroupReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasName_:1;
  SInt64 groupId;
  NSString* name;
  NSMutableArray * membersArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasName;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSArray<AccountInfo*> * members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (InvitedJoinGroupReqBuilder*) builder;
+ (InvitedJoinGroupReqBuilder*) builder;
+ (InvitedJoinGroupReqBuilder*) builderWithPrototype:(InvitedJoinGroupReq*) prototype;
- (InvitedJoinGroupReqBuilder*) toBuilder;

+ (InvitedJoinGroupReq*) parseFromData:(NSData*) data;
+ (InvitedJoinGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InvitedJoinGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (InvitedJoinGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InvitedJoinGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (InvitedJoinGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface InvitedJoinGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  InvitedJoinGroupReq* resultInvitedJoinGroupReq;
}

- (InvitedJoinGroupReq*) defaultInstance;

- (InvitedJoinGroupReqBuilder*) clear;
- (InvitedJoinGroupReqBuilder*) clone;

- (InvitedJoinGroupReq*) build;
- (InvitedJoinGroupReq*) buildPartial;

- (InvitedJoinGroupReqBuilder*) mergeFrom:(InvitedJoinGroupReq*) other;
- (InvitedJoinGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (InvitedJoinGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (InvitedJoinGroupReqBuilder*) setGroupId:(SInt64) value;
- (InvitedJoinGroupReqBuilder*) clearGroupId;

- (BOOL) hasName;
- (NSString*) name;
- (InvitedJoinGroupReqBuilder*) setName:(NSString*) value;
- (InvitedJoinGroupReqBuilder*) clearName;

- (NSMutableArray<AccountInfo*> *)members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;
- (InvitedJoinGroupReqBuilder *)addMembers:(AccountInfo*)value;
- (InvitedJoinGroupReqBuilder *)setMembersArray:(NSArray<AccountInfo*> *)array;
- (InvitedJoinGroupReqBuilder *)clearMembers;
@end

#define InvitedJoinGroupResp_status @"status"
#define InvitedJoinGroupResp_group_timestamp @"groupTimestamp"
@interface InvitedJoinGroupResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (InvitedJoinGroupRespBuilder*) builder;
+ (InvitedJoinGroupRespBuilder*) builder;
+ (InvitedJoinGroupRespBuilder*) builderWithPrototype:(InvitedJoinGroupResp*) prototype;
- (InvitedJoinGroupRespBuilder*) toBuilder;

+ (InvitedJoinGroupResp*) parseFromData:(NSData*) data;
+ (InvitedJoinGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InvitedJoinGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (InvitedJoinGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InvitedJoinGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (InvitedJoinGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface InvitedJoinGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  InvitedJoinGroupResp* resultInvitedJoinGroupResp;
}

- (InvitedJoinGroupResp*) defaultInstance;

- (InvitedJoinGroupRespBuilder*) clear;
- (InvitedJoinGroupRespBuilder*) clone;

- (InvitedJoinGroupResp*) build;
- (InvitedJoinGroupResp*) buildPartial;

- (InvitedJoinGroupRespBuilder*) mergeFrom:(InvitedJoinGroupResp*) other;
- (InvitedJoinGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (InvitedJoinGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (InvitedJoinGroupRespBuilder*) setStatus:(EIMRespHeader*) value;
- (InvitedJoinGroupRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (InvitedJoinGroupRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (InvitedJoinGroupRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (InvitedJoinGroupRespBuilder*) setGroupTimestamp:(UInt64) value;
- (InvitedJoinGroupRespBuilder*) clearGroupTimestamp;
@end

#define DeleteGroupUserReq_group_id @"groupId"
#define DeleteGroupUserReq_members @"members"
@interface DeleteGroupUserReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  SInt64 groupId;
  NSMutableArray * membersArray;
}
- (BOOL) hasGroupId;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSArray<AccountInfo*> * members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeleteGroupUserReqBuilder*) builder;
+ (DeleteGroupUserReqBuilder*) builder;
+ (DeleteGroupUserReqBuilder*) builderWithPrototype:(DeleteGroupUserReq*) prototype;
- (DeleteGroupUserReqBuilder*) toBuilder;

+ (DeleteGroupUserReq*) parseFromData:(NSData*) data;
+ (DeleteGroupUserReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteGroupUserReq*) parseFromInputStream:(NSInputStream*) input;
+ (DeleteGroupUserReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteGroupUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeleteGroupUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeleteGroupUserReqBuilder : PBGeneratedMessageBuilder {
@private
  DeleteGroupUserReq* resultDeleteGroupUserReq;
}

- (DeleteGroupUserReq*) defaultInstance;

- (DeleteGroupUserReqBuilder*) clear;
- (DeleteGroupUserReqBuilder*) clone;

- (DeleteGroupUserReq*) build;
- (DeleteGroupUserReq*) buildPartial;

- (DeleteGroupUserReqBuilder*) mergeFrom:(DeleteGroupUserReq*) other;
- (DeleteGroupUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeleteGroupUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (DeleteGroupUserReqBuilder*) setGroupId:(SInt64) value;
- (DeleteGroupUserReqBuilder*) clearGroupId;

- (NSMutableArray<AccountInfo*> *)members;
- (AccountInfo*)membersAtIndex:(NSUInteger)index;
- (DeleteGroupUserReqBuilder *)addMembers:(AccountInfo*)value;
- (DeleteGroupUserReqBuilder *)setMembersArray:(NSArray<AccountInfo*> *)array;
- (DeleteGroupUserReqBuilder *)clearMembers;
@end

#define DeleteGroupUserResp_status @"status"
#define DeleteGroupUserResp_group_timestamp @"groupTimestamp"
@interface DeleteGroupUserResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeleteGroupUserRespBuilder*) builder;
+ (DeleteGroupUserRespBuilder*) builder;
+ (DeleteGroupUserRespBuilder*) builderWithPrototype:(DeleteGroupUserResp*) prototype;
- (DeleteGroupUserRespBuilder*) toBuilder;

+ (DeleteGroupUserResp*) parseFromData:(NSData*) data;
+ (DeleteGroupUserResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteGroupUserResp*) parseFromInputStream:(NSInputStream*) input;
+ (DeleteGroupUserResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteGroupUserResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeleteGroupUserResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeleteGroupUserRespBuilder : PBGeneratedMessageBuilder {
@private
  DeleteGroupUserResp* resultDeleteGroupUserResp;
}

- (DeleteGroupUserResp*) defaultInstance;

- (DeleteGroupUserRespBuilder*) clear;
- (DeleteGroupUserRespBuilder*) clone;

- (DeleteGroupUserResp*) build;
- (DeleteGroupUserResp*) buildPartial;

- (DeleteGroupUserRespBuilder*) mergeFrom:(DeleteGroupUserResp*) other;
- (DeleteGroupUserRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeleteGroupUserRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (DeleteGroupUserRespBuilder*) setStatus:(EIMRespHeader*) value;
- (DeleteGroupUserRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (DeleteGroupUserRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (DeleteGroupUserRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (DeleteGroupUserRespBuilder*) setGroupTimestamp:(UInt64) value;
- (DeleteGroupUserRespBuilder*) clearGroupTimestamp;
@end

#define TransferGroupOwnerReq_group_id @"groupId"
#define TransferGroupOwnerReq_member @"member"
@interface TransferGroupOwnerReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasMember_:1;
  SInt64 groupId;
  AccountInfo* member;
}
- (BOOL) hasGroupId;
- (BOOL) hasMember;
@property (readonly) SInt64 groupId;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TransferGroupOwnerReqBuilder*) builder;
+ (TransferGroupOwnerReqBuilder*) builder;
+ (TransferGroupOwnerReqBuilder*) builderWithPrototype:(TransferGroupOwnerReq*) prototype;
- (TransferGroupOwnerReqBuilder*) toBuilder;

+ (TransferGroupOwnerReq*) parseFromData:(NSData*) data;
+ (TransferGroupOwnerReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TransferGroupOwnerReq*) parseFromInputStream:(NSInputStream*) input;
+ (TransferGroupOwnerReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TransferGroupOwnerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TransferGroupOwnerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TransferGroupOwnerReqBuilder : PBGeneratedMessageBuilder {
@private
  TransferGroupOwnerReq* resultTransferGroupOwnerReq;
}

- (TransferGroupOwnerReq*) defaultInstance;

- (TransferGroupOwnerReqBuilder*) clear;
- (TransferGroupOwnerReqBuilder*) clone;

- (TransferGroupOwnerReq*) build;
- (TransferGroupOwnerReq*) buildPartial;

- (TransferGroupOwnerReqBuilder*) mergeFrom:(TransferGroupOwnerReq*) other;
- (TransferGroupOwnerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TransferGroupOwnerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (TransferGroupOwnerReqBuilder*) setGroupId:(SInt64) value;
- (TransferGroupOwnerReqBuilder*) clearGroupId;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (TransferGroupOwnerReqBuilder*) setMember:(AccountInfo*) value;
- (TransferGroupOwnerReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (TransferGroupOwnerReqBuilder*) mergeMember:(AccountInfo*) value;
- (TransferGroupOwnerReqBuilder*) clearMember;
@end

#define TransferGroupOwnerResp_status @"status"
#define TransferGroupOwnerResp_group_timestamp @"groupTimestamp"
@interface TransferGroupOwnerResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TransferGroupOwnerRespBuilder*) builder;
+ (TransferGroupOwnerRespBuilder*) builder;
+ (TransferGroupOwnerRespBuilder*) builderWithPrototype:(TransferGroupOwnerResp*) prototype;
- (TransferGroupOwnerRespBuilder*) toBuilder;

+ (TransferGroupOwnerResp*) parseFromData:(NSData*) data;
+ (TransferGroupOwnerResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TransferGroupOwnerResp*) parseFromInputStream:(NSInputStream*) input;
+ (TransferGroupOwnerResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TransferGroupOwnerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TransferGroupOwnerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TransferGroupOwnerRespBuilder : PBGeneratedMessageBuilder {
@private
  TransferGroupOwnerResp* resultTransferGroupOwnerResp;
}

- (TransferGroupOwnerResp*) defaultInstance;

- (TransferGroupOwnerRespBuilder*) clear;
- (TransferGroupOwnerRespBuilder*) clone;

- (TransferGroupOwnerResp*) build;
- (TransferGroupOwnerResp*) buildPartial;

- (TransferGroupOwnerRespBuilder*) mergeFrom:(TransferGroupOwnerResp*) other;
- (TransferGroupOwnerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TransferGroupOwnerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (TransferGroupOwnerRespBuilder*) setStatus:(EIMRespHeader*) value;
- (TransferGroupOwnerRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (TransferGroupOwnerRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (TransferGroupOwnerRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (TransferGroupOwnerRespBuilder*) setGroupTimestamp:(UInt64) value;
- (TransferGroupOwnerRespBuilder*) clearGroupTimestamp;
@end

#define SetManagerReq_group_id @"groupId"
#define SetManagerReq_member @"member"
@interface SetManagerReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  SInt64 groupId;
  NSMutableArray * memberArray;
}
- (BOOL) hasGroupId;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSArray<AccountInfo*> * member;
- (AccountInfo*)memberAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetManagerReqBuilder*) builder;
+ (SetManagerReqBuilder*) builder;
+ (SetManagerReqBuilder*) builderWithPrototype:(SetManagerReq*) prototype;
- (SetManagerReqBuilder*) toBuilder;

+ (SetManagerReq*) parseFromData:(NSData*) data;
+ (SetManagerReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetManagerReq*) parseFromInputStream:(NSInputStream*) input;
+ (SetManagerReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetManagerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetManagerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetManagerReqBuilder : PBGeneratedMessageBuilder {
@private
  SetManagerReq* resultSetManagerReq;
}

- (SetManagerReq*) defaultInstance;

- (SetManagerReqBuilder*) clear;
- (SetManagerReqBuilder*) clone;

- (SetManagerReq*) build;
- (SetManagerReq*) buildPartial;

- (SetManagerReqBuilder*) mergeFrom:(SetManagerReq*) other;
- (SetManagerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetManagerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (SetManagerReqBuilder*) setGroupId:(SInt64) value;
- (SetManagerReqBuilder*) clearGroupId;

- (NSMutableArray<AccountInfo*> *)member;
- (AccountInfo*)memberAtIndex:(NSUInteger)index;
- (SetManagerReqBuilder *)addMember:(AccountInfo*)value;
- (SetManagerReqBuilder *)setMemberArray:(NSArray<AccountInfo*> *)array;
- (SetManagerReqBuilder *)clearMember;
@end

#define SetManagerResp_status @"status"
#define SetManagerResp_group_timestamp @"groupTimestamp"
@interface SetManagerResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetManagerRespBuilder*) builder;
+ (SetManagerRespBuilder*) builder;
+ (SetManagerRespBuilder*) builderWithPrototype:(SetManagerResp*) prototype;
- (SetManagerRespBuilder*) toBuilder;

+ (SetManagerResp*) parseFromData:(NSData*) data;
+ (SetManagerResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetManagerResp*) parseFromInputStream:(NSInputStream*) input;
+ (SetManagerResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetManagerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetManagerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetManagerRespBuilder : PBGeneratedMessageBuilder {
@private
  SetManagerResp* resultSetManagerResp;
}

- (SetManagerResp*) defaultInstance;

- (SetManagerRespBuilder*) clear;
- (SetManagerRespBuilder*) clone;

- (SetManagerResp*) build;
- (SetManagerResp*) buildPartial;

- (SetManagerRespBuilder*) mergeFrom:(SetManagerResp*) other;
- (SetManagerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetManagerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (SetManagerRespBuilder*) setStatus:(EIMRespHeader*) value;
- (SetManagerRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (SetManagerRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (SetManagerRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (SetManagerRespBuilder*) setGroupTimestamp:(UInt64) value;
- (SetManagerRespBuilder*) clearGroupTimestamp;
@end

#define DeleteManagerReq_group_id @"groupId"
#define DeleteManagerReq_member @"member"
@interface DeleteManagerReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  SInt64 groupId;
  NSMutableArray * memberArray;
}
- (BOOL) hasGroupId;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSArray<AccountInfo*> * member;
- (AccountInfo*)memberAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeleteManagerReqBuilder*) builder;
+ (DeleteManagerReqBuilder*) builder;
+ (DeleteManagerReqBuilder*) builderWithPrototype:(DeleteManagerReq*) prototype;
- (DeleteManagerReqBuilder*) toBuilder;

+ (DeleteManagerReq*) parseFromData:(NSData*) data;
+ (DeleteManagerReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteManagerReq*) parseFromInputStream:(NSInputStream*) input;
+ (DeleteManagerReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteManagerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeleteManagerReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeleteManagerReqBuilder : PBGeneratedMessageBuilder {
@private
  DeleteManagerReq* resultDeleteManagerReq;
}

- (DeleteManagerReq*) defaultInstance;

- (DeleteManagerReqBuilder*) clear;
- (DeleteManagerReqBuilder*) clone;

- (DeleteManagerReq*) build;
- (DeleteManagerReq*) buildPartial;

- (DeleteManagerReqBuilder*) mergeFrom:(DeleteManagerReq*) other;
- (DeleteManagerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeleteManagerReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (DeleteManagerReqBuilder*) setGroupId:(SInt64) value;
- (DeleteManagerReqBuilder*) clearGroupId;

- (NSMutableArray<AccountInfo*> *)member;
- (AccountInfo*)memberAtIndex:(NSUInteger)index;
- (DeleteManagerReqBuilder *)addMember:(AccountInfo*)value;
- (DeleteManagerReqBuilder *)setMemberArray:(NSArray<AccountInfo*> *)array;
- (DeleteManagerReqBuilder *)clearMember;
@end

#define DeleteManagerResp_status @"status"
#define DeleteManagerResp_group_timestamp @"groupTimestamp"
@interface DeleteManagerResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeleteManagerRespBuilder*) builder;
+ (DeleteManagerRespBuilder*) builder;
+ (DeleteManagerRespBuilder*) builderWithPrototype:(DeleteManagerResp*) prototype;
- (DeleteManagerRespBuilder*) toBuilder;

+ (DeleteManagerResp*) parseFromData:(NSData*) data;
+ (DeleteManagerResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteManagerResp*) parseFromInputStream:(NSInputStream*) input;
+ (DeleteManagerResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeleteManagerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeleteManagerResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeleteManagerRespBuilder : PBGeneratedMessageBuilder {
@private
  DeleteManagerResp* resultDeleteManagerResp;
}

- (DeleteManagerResp*) defaultInstance;

- (DeleteManagerRespBuilder*) clear;
- (DeleteManagerRespBuilder*) clone;

- (DeleteManagerResp*) build;
- (DeleteManagerResp*) buildPartial;

- (DeleteManagerRespBuilder*) mergeFrom:(DeleteManagerResp*) other;
- (DeleteManagerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeleteManagerRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (DeleteManagerRespBuilder*) setStatus:(EIMRespHeader*) value;
- (DeleteManagerRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (DeleteManagerRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (DeleteManagerRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (DeleteManagerRespBuilder*) setGroupTimestamp:(UInt64) value;
- (DeleteManagerRespBuilder*) clearGroupTimestamp;
@end

#define SetGroupAnnouncementReq_group_id @"groupId"
#define SetGroupAnnouncementReq_announcement @"announcement"
@interface SetGroupAnnouncementReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasAnnouncement_:1;
  SInt64 groupId;
  NSString* announcement;
}
- (BOOL) hasGroupId;
- (BOOL) hasAnnouncement;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* announcement;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupAnnouncementReqBuilder*) builder;
+ (SetGroupAnnouncementReqBuilder*) builder;
+ (SetGroupAnnouncementReqBuilder*) builderWithPrototype:(SetGroupAnnouncementReq*) prototype;
- (SetGroupAnnouncementReqBuilder*) toBuilder;

+ (SetGroupAnnouncementReq*) parseFromData:(NSData*) data;
+ (SetGroupAnnouncementReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupAnnouncementReq*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupAnnouncementReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupAnnouncementReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupAnnouncementReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupAnnouncementReqBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupAnnouncementReq* resultSetGroupAnnouncementReq;
}

- (SetGroupAnnouncementReq*) defaultInstance;

- (SetGroupAnnouncementReqBuilder*) clear;
- (SetGroupAnnouncementReqBuilder*) clone;

- (SetGroupAnnouncementReq*) build;
- (SetGroupAnnouncementReq*) buildPartial;

- (SetGroupAnnouncementReqBuilder*) mergeFrom:(SetGroupAnnouncementReq*) other;
- (SetGroupAnnouncementReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupAnnouncementReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (SetGroupAnnouncementReqBuilder*) setGroupId:(SInt64) value;
- (SetGroupAnnouncementReqBuilder*) clearGroupId;

- (BOOL) hasAnnouncement;
- (NSString*) announcement;
- (SetGroupAnnouncementReqBuilder*) setAnnouncement:(NSString*) value;
- (SetGroupAnnouncementReqBuilder*) clearAnnouncement;
@end

#define SetGroupAnnouncementResp_status @"status"
#define SetGroupAnnouncementResp_group_timestamp @"groupTimestamp"
@interface SetGroupAnnouncementResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupAnnouncementRespBuilder*) builder;
+ (SetGroupAnnouncementRespBuilder*) builder;
+ (SetGroupAnnouncementRespBuilder*) builderWithPrototype:(SetGroupAnnouncementResp*) prototype;
- (SetGroupAnnouncementRespBuilder*) toBuilder;

+ (SetGroupAnnouncementResp*) parseFromData:(NSData*) data;
+ (SetGroupAnnouncementResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupAnnouncementResp*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupAnnouncementResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupAnnouncementResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupAnnouncementResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupAnnouncementRespBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupAnnouncementResp* resultSetGroupAnnouncementResp;
}

- (SetGroupAnnouncementResp*) defaultInstance;

- (SetGroupAnnouncementRespBuilder*) clear;
- (SetGroupAnnouncementRespBuilder*) clone;

- (SetGroupAnnouncementResp*) build;
- (SetGroupAnnouncementResp*) buildPartial;

- (SetGroupAnnouncementRespBuilder*) mergeFrom:(SetGroupAnnouncementResp*) other;
- (SetGroupAnnouncementRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupAnnouncementRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (SetGroupAnnouncementRespBuilder*) setStatus:(EIMRespHeader*) value;
- (SetGroupAnnouncementRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (SetGroupAnnouncementRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (SetGroupAnnouncementRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (SetGroupAnnouncementRespBuilder*) setGroupTimestamp:(UInt64) value;
- (SetGroupAnnouncementRespBuilder*) clearGroupTimestamp;
@end

#define SetGroupNameReq_group_id @"groupId"
#define SetGroupNameReq_name @"name"
@interface SetGroupNameReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasName_:1;
  SInt64 groupId;
  NSString* name;
}
- (BOOL) hasGroupId;
- (BOOL) hasName;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* name;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupNameReqBuilder*) builder;
+ (SetGroupNameReqBuilder*) builder;
+ (SetGroupNameReqBuilder*) builderWithPrototype:(SetGroupNameReq*) prototype;
- (SetGroupNameReqBuilder*) toBuilder;

+ (SetGroupNameReq*) parseFromData:(NSData*) data;
+ (SetGroupNameReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupNameReq*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupNameReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupNameReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupNameReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupNameReqBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupNameReq* resultSetGroupNameReq;
}

- (SetGroupNameReq*) defaultInstance;

- (SetGroupNameReqBuilder*) clear;
- (SetGroupNameReqBuilder*) clone;

- (SetGroupNameReq*) build;
- (SetGroupNameReq*) buildPartial;

- (SetGroupNameReqBuilder*) mergeFrom:(SetGroupNameReq*) other;
- (SetGroupNameReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupNameReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (SetGroupNameReqBuilder*) setGroupId:(SInt64) value;
- (SetGroupNameReqBuilder*) clearGroupId;

- (BOOL) hasName;
- (NSString*) name;
- (SetGroupNameReqBuilder*) setName:(NSString*) value;
- (SetGroupNameReqBuilder*) clearName;
@end

#define SetGroupNameResp_status @"status"
#define SetGroupNameResp_group_timestamp @"groupTimestamp"
@interface SetGroupNameResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupNameRespBuilder*) builder;
+ (SetGroupNameRespBuilder*) builder;
+ (SetGroupNameRespBuilder*) builderWithPrototype:(SetGroupNameResp*) prototype;
- (SetGroupNameRespBuilder*) toBuilder;

+ (SetGroupNameResp*) parseFromData:(NSData*) data;
+ (SetGroupNameResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupNameResp*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupNameResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupNameResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupNameResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupNameRespBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupNameResp* resultSetGroupNameResp;
}

- (SetGroupNameResp*) defaultInstance;

- (SetGroupNameRespBuilder*) clear;
- (SetGroupNameRespBuilder*) clone;

- (SetGroupNameResp*) build;
- (SetGroupNameResp*) buildPartial;

- (SetGroupNameRespBuilder*) mergeFrom:(SetGroupNameResp*) other;
- (SetGroupNameRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupNameRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (SetGroupNameRespBuilder*) setStatus:(EIMRespHeader*) value;
- (SetGroupNameRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (SetGroupNameRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (SetGroupNameRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (SetGroupNameRespBuilder*) setGroupTimestamp:(UInt64) value;
- (SetGroupNameRespBuilder*) clearGroupTimestamp;
@end

#define SetGroupUserNickNameReq_group_id @"groupId"
#define SetGroupUserNickNameReq_nick_name @"nickName"
@interface SetGroupUserNickNameReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasNickName_:1;
  SInt64 groupId;
  NSString* nickName;
}
- (BOOL) hasGroupId;
- (BOOL) hasNickName;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* nickName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupUserNickNameReqBuilder*) builder;
+ (SetGroupUserNickNameReqBuilder*) builder;
+ (SetGroupUserNickNameReqBuilder*) builderWithPrototype:(SetGroupUserNickNameReq*) prototype;
- (SetGroupUserNickNameReqBuilder*) toBuilder;

+ (SetGroupUserNickNameReq*) parseFromData:(NSData*) data;
+ (SetGroupUserNickNameReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupUserNickNameReq*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupUserNickNameReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupUserNickNameReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupUserNickNameReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupUserNickNameReqBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupUserNickNameReq* resultSetGroupUserNickNameReq;
}

- (SetGroupUserNickNameReq*) defaultInstance;

- (SetGroupUserNickNameReqBuilder*) clear;
- (SetGroupUserNickNameReqBuilder*) clone;

- (SetGroupUserNickNameReq*) build;
- (SetGroupUserNickNameReq*) buildPartial;

- (SetGroupUserNickNameReqBuilder*) mergeFrom:(SetGroupUserNickNameReq*) other;
- (SetGroupUserNickNameReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupUserNickNameReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (SetGroupUserNickNameReqBuilder*) setGroupId:(SInt64) value;
- (SetGroupUserNickNameReqBuilder*) clearGroupId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (SetGroupUserNickNameReqBuilder*) setNickName:(NSString*) value;
- (SetGroupUserNickNameReqBuilder*) clearNickName;
@end

#define SetGroupUserNickNameResp_status @"status"
#define SetGroupUserNickNameResp_group_timestamp @"groupTimestamp"
@interface SetGroupUserNickNameResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupTimestamp_:1;
  BOOL hasStatus_:1;
  UInt64 groupTimestamp;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
- (BOOL) hasGroupTimestamp;
@property (readonly, strong) EIMRespHeader* status;
@property (readonly) UInt64 groupTimestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupUserNickNameRespBuilder*) builder;
+ (SetGroupUserNickNameRespBuilder*) builder;
+ (SetGroupUserNickNameRespBuilder*) builderWithPrototype:(SetGroupUserNickNameResp*) prototype;
- (SetGroupUserNickNameRespBuilder*) toBuilder;

+ (SetGroupUserNickNameResp*) parseFromData:(NSData*) data;
+ (SetGroupUserNickNameResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupUserNickNameResp*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupUserNickNameResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupUserNickNameResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupUserNickNameResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupUserNickNameRespBuilder : PBGeneratedMessageBuilder {
@private
  SetGroupUserNickNameResp* resultSetGroupUserNickNameResp;
}

- (SetGroupUserNickNameResp*) defaultInstance;

- (SetGroupUserNickNameRespBuilder*) clear;
- (SetGroupUserNickNameRespBuilder*) clone;

- (SetGroupUserNickNameResp*) build;
- (SetGroupUserNickNameResp*) buildPartial;

- (SetGroupUserNickNameRespBuilder*) mergeFrom:(SetGroupUserNickNameResp*) other;
- (SetGroupUserNickNameRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupUserNickNameRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (SetGroupUserNickNameRespBuilder*) setStatus:(EIMRespHeader*) value;
- (SetGroupUserNickNameRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (SetGroupUserNickNameRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (SetGroupUserNickNameRespBuilder*) clearStatus;

- (BOOL) hasGroupTimestamp;
- (UInt64) groupTimestamp;
- (SetGroupUserNickNameRespBuilder*) setGroupTimestamp:(UInt64) value;
- (SetGroupUserNickNameRespBuilder*) clearGroupTimestamp;
@end

#define QuitGroupReq_group_id @"groupId"
#define QuitGroupReq_nick_name @"nickName"
@interface QuitGroupReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasNickName_:1;
  SInt64 groupId;
  NSString* nickName;
}
- (BOOL) hasGroupId;
- (BOOL) hasNickName;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* nickName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QuitGroupReqBuilder*) builder;
+ (QuitGroupReqBuilder*) builder;
+ (QuitGroupReqBuilder*) builderWithPrototype:(QuitGroupReq*) prototype;
- (QuitGroupReqBuilder*) toBuilder;

+ (QuitGroupReq*) parseFromData:(NSData*) data;
+ (QuitGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuitGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (QuitGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuitGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QuitGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QuitGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  QuitGroupReq* resultQuitGroupReq;
}

- (QuitGroupReq*) defaultInstance;

- (QuitGroupReqBuilder*) clear;
- (QuitGroupReqBuilder*) clone;

- (QuitGroupReq*) build;
- (QuitGroupReq*) buildPartial;

- (QuitGroupReqBuilder*) mergeFrom:(QuitGroupReq*) other;
- (QuitGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QuitGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (QuitGroupReqBuilder*) setGroupId:(SInt64) value;
- (QuitGroupReqBuilder*) clearGroupId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (QuitGroupReqBuilder*) setNickName:(NSString*) value;
- (QuitGroupReqBuilder*) clearNickName;
@end

#define QuitGroupResp_status @"status"
@interface QuitGroupResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QuitGroupRespBuilder*) builder;
+ (QuitGroupRespBuilder*) builder;
+ (QuitGroupRespBuilder*) builderWithPrototype:(QuitGroupResp*) prototype;
- (QuitGroupRespBuilder*) toBuilder;

+ (QuitGroupResp*) parseFromData:(NSData*) data;
+ (QuitGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuitGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (QuitGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuitGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QuitGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QuitGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  QuitGroupResp* resultQuitGroupResp;
}

- (QuitGroupResp*) defaultInstance;

- (QuitGroupRespBuilder*) clear;
- (QuitGroupRespBuilder*) clone;

- (QuitGroupResp*) build;
- (QuitGroupResp*) buildPartial;

- (QuitGroupRespBuilder*) mergeFrom:(QuitGroupResp*) other;
- (QuitGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QuitGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (QuitGroupRespBuilder*) setStatus:(EIMRespHeader*) value;
- (QuitGroupRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (QuitGroupRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (QuitGroupRespBuilder*) clearStatus;
@end

#define ReportRunStatusReq_status @"status"
@interface ReportRunStatusReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  NSString* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) NSString* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReportRunStatusReqBuilder*) builder;
+ (ReportRunStatusReqBuilder*) builder;
+ (ReportRunStatusReqBuilder*) builderWithPrototype:(ReportRunStatusReq*) prototype;
- (ReportRunStatusReqBuilder*) toBuilder;

+ (ReportRunStatusReq*) parseFromData:(NSData*) data;
+ (ReportRunStatusReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReportRunStatusReq*) parseFromInputStream:(NSInputStream*) input;
+ (ReportRunStatusReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReportRunStatusReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReportRunStatusReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReportRunStatusReqBuilder : PBGeneratedMessageBuilder {
@private
  ReportRunStatusReq* resultReportRunStatusReq;
}

- (ReportRunStatusReq*) defaultInstance;

- (ReportRunStatusReqBuilder*) clear;
- (ReportRunStatusReqBuilder*) clone;

- (ReportRunStatusReq*) build;
- (ReportRunStatusReq*) buildPartial;

- (ReportRunStatusReqBuilder*) mergeFrom:(ReportRunStatusReq*) other;
- (ReportRunStatusReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReportRunStatusReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (NSString*) status;
- (ReportRunStatusReqBuilder*) setStatus:(NSString*) value;
- (ReportRunStatusReqBuilder*) clearStatus;
@end

#define ReportRunStatusResp_status @"status"
@interface ReportRunStatusResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReportRunStatusRespBuilder*) builder;
+ (ReportRunStatusRespBuilder*) builder;
+ (ReportRunStatusRespBuilder*) builderWithPrototype:(ReportRunStatusResp*) prototype;
- (ReportRunStatusRespBuilder*) toBuilder;

+ (ReportRunStatusResp*) parseFromData:(NSData*) data;
+ (ReportRunStatusResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReportRunStatusResp*) parseFromInputStream:(NSInputStream*) input;
+ (ReportRunStatusResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReportRunStatusResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReportRunStatusResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReportRunStatusRespBuilder : PBGeneratedMessageBuilder {
@private
  ReportRunStatusResp* resultReportRunStatusResp;
}

- (ReportRunStatusResp*) defaultInstance;

- (ReportRunStatusRespBuilder*) clear;
- (ReportRunStatusRespBuilder*) clone;

- (ReportRunStatusResp*) build;
- (ReportRunStatusResp*) buildPartial;

- (ReportRunStatusRespBuilder*) mergeFrom:(ReportRunStatusResp*) other;
- (ReportRunStatusRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReportRunStatusRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (ReportRunStatusRespBuilder*) setStatus:(EIMRespHeader*) value;
- (ReportRunStatusRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (ReportRunStatusRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (ReportRunStatusRespBuilder*) clearStatus;
@end

#define JoinGroupReq_group_id @"groupId"
#define JoinGroupReq_member @"member"
@interface JoinGroupReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasGroupId_:1;
  BOOL hasMember_:1;
  SInt64 groupId;
  AccountInfo* member;
}
- (BOOL) hasGroupId;
- (BOOL) hasMember;
@property (readonly) SInt64 groupId;
@property (readonly, strong) AccountInfo* member;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (JoinGroupReqBuilder*) builder;
+ (JoinGroupReqBuilder*) builder;
+ (JoinGroupReqBuilder*) builderWithPrototype:(JoinGroupReq*) prototype;
- (JoinGroupReqBuilder*) toBuilder;

+ (JoinGroupReq*) parseFromData:(NSData*) data;
+ (JoinGroupReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinGroupReq*) parseFromInputStream:(NSInputStream*) input;
+ (JoinGroupReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (JoinGroupReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface JoinGroupReqBuilder : PBGeneratedMessageBuilder {
@private
  JoinGroupReq* resultJoinGroupReq;
}

- (JoinGroupReq*) defaultInstance;

- (JoinGroupReqBuilder*) clear;
- (JoinGroupReqBuilder*) clone;

- (JoinGroupReq*) build;
- (JoinGroupReq*) buildPartial;

- (JoinGroupReqBuilder*) mergeFrom:(JoinGroupReq*) other;
- (JoinGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (JoinGroupReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (JoinGroupReqBuilder*) setGroupId:(SInt64) value;
- (JoinGroupReqBuilder*) clearGroupId;

- (BOOL) hasMember;
- (AccountInfo*) member;
- (JoinGroupReqBuilder*) setMember:(AccountInfo*) value;
- (JoinGroupReqBuilder*) setMemberBuilder:(AccountInfoBuilder*) builderForValue;
- (JoinGroupReqBuilder*) mergeMember:(AccountInfo*) value;
- (JoinGroupReqBuilder*) clearMember;
@end

#define JoinGroupResp_status @"status"
@interface JoinGroupResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (JoinGroupRespBuilder*) builder;
+ (JoinGroupRespBuilder*) builder;
+ (JoinGroupRespBuilder*) builderWithPrototype:(JoinGroupResp*) prototype;
- (JoinGroupRespBuilder*) toBuilder;

+ (JoinGroupResp*) parseFromData:(NSData*) data;
+ (JoinGroupResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinGroupResp*) parseFromInputStream:(NSInputStream*) input;
+ (JoinGroupResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (JoinGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (JoinGroupResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface JoinGroupRespBuilder : PBGeneratedMessageBuilder {
@private
  JoinGroupResp* resultJoinGroupResp;
}

- (JoinGroupResp*) defaultInstance;

- (JoinGroupRespBuilder*) clear;
- (JoinGroupRespBuilder*) clone;

- (JoinGroupResp*) build;
- (JoinGroupResp*) buildPartial;

- (JoinGroupRespBuilder*) mergeFrom:(JoinGroupResp*) other;
- (JoinGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (JoinGroupRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (JoinGroupRespBuilder*) setStatus:(EIMRespHeader*) value;
- (JoinGroupRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (JoinGroupRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (JoinGroupRespBuilder*) clearStatus;
@end

#define CreateGroupNotificationReq_notification @"notification"
#define CreateGroupNotificationReq_group_id @"groupId"
@interface CreateGroupNotificationReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNotification_:1;
  BOOL hasGroupId_:1;
  BOOL notification_:1;
  SInt64 groupId;
}
- (BOOL) hasNotification;
- (BOOL) hasGroupId;
- (BOOL) notification;
@property (readonly) SInt64 groupId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupNotificationReqBuilder*) builder;
+ (CreateGroupNotificationReqBuilder*) builder;
+ (CreateGroupNotificationReqBuilder*) builderWithPrototype:(CreateGroupNotificationReq*) prototype;
- (CreateGroupNotificationReqBuilder*) toBuilder;

+ (CreateGroupNotificationReq*) parseFromData:(NSData*) data;
+ (CreateGroupNotificationReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupNotificationReq*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupNotificationReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupNotificationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupNotificationReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupNotificationReqBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupNotificationReq* resultCreateGroupNotificationReq;
}

- (CreateGroupNotificationReq*) defaultInstance;

- (CreateGroupNotificationReqBuilder*) clear;
- (CreateGroupNotificationReqBuilder*) clone;

- (CreateGroupNotificationReq*) build;
- (CreateGroupNotificationReq*) buildPartial;

- (CreateGroupNotificationReqBuilder*) mergeFrom:(CreateGroupNotificationReq*) other;
- (CreateGroupNotificationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupNotificationReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNotification;
- (BOOL) notification;
- (CreateGroupNotificationReqBuilder*) setNotification:(BOOL) value;
- (CreateGroupNotificationReqBuilder*) clearNotification;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (CreateGroupNotificationReqBuilder*) setGroupId:(SInt64) value;
- (CreateGroupNotificationReqBuilder*) clearGroupId;
@end

#define CreateGroupNotificationResp_status @"status"
@interface CreateGroupNotificationResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CreateGroupNotificationRespBuilder*) builder;
+ (CreateGroupNotificationRespBuilder*) builder;
+ (CreateGroupNotificationRespBuilder*) builderWithPrototype:(CreateGroupNotificationResp*) prototype;
- (CreateGroupNotificationRespBuilder*) toBuilder;

+ (CreateGroupNotificationResp*) parseFromData:(NSData*) data;
+ (CreateGroupNotificationResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupNotificationResp*) parseFromInputStream:(NSInputStream*) input;
+ (CreateGroupNotificationResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CreateGroupNotificationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CreateGroupNotificationResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CreateGroupNotificationRespBuilder : PBGeneratedMessageBuilder {
@private
  CreateGroupNotificationResp* resultCreateGroupNotificationResp;
}

- (CreateGroupNotificationResp*) defaultInstance;

- (CreateGroupNotificationRespBuilder*) clear;
- (CreateGroupNotificationRespBuilder*) clone;

- (CreateGroupNotificationResp*) build;
- (CreateGroupNotificationResp*) buildPartial;

- (CreateGroupNotificationRespBuilder*) mergeFrom:(CreateGroupNotificationResp*) other;
- (CreateGroupNotificationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CreateGroupNotificationRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (CreateGroupNotificationRespBuilder*) setStatus:(EIMRespHeader*) value;
- (CreateGroupNotificationRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (CreateGroupNotificationRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (CreateGroupNotificationRespBuilder*) clearStatus;
@end


// @@protoc_insertion_point(global_scope)
