// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Eim_message.pb.h"
// @@protoc_insertion_point(imports)

@class AuthReq;
@class AuthReqBuilder;
@class AuthResp;
@class AuthRespBuilder;
@class BaseResultResp;
@class BaseResultRespBuilder;
@class EIMRespHeader;
@class EIMRespHeaderBuilder;
@class GroupMessageReq;
@class GroupMessageReqBuilder;
@class HearBeatReq;
@class HearBeatReqBuilder;
@class HearBeatResp;
@class HearBeatRespBuilder;
@class MessageReq;
@class MessageReqBuilder;
@class MessageResp;
@class MessageRespBuilder;
@class PullMessageReq;
@class PullMessageReqBuilder;
@class PullMessageResp;
@class PullMessageRespBuilder;
@class SendMessageResp;
@class SendMessageRespBuilder;



@interface EimBaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define BaseResultResp_status @"status"
@interface BaseResultResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  EIMRespHeader* status;
}
- (BOOL) hasStatus;
@property (readonly, strong) EIMRespHeader* status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BaseResultRespBuilder*) builder;
+ (BaseResultRespBuilder*) builder;
+ (BaseResultRespBuilder*) builderWithPrototype:(BaseResultResp*) prototype;
- (BaseResultRespBuilder*) toBuilder;

+ (BaseResultResp*) parseFromData:(NSData*) data;
+ (BaseResultResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseResultResp*) parseFromInputStream:(NSInputStream*) input;
+ (BaseResultResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseResultResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BaseResultResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BaseResultRespBuilder : PBGeneratedMessageBuilder {
@private
  BaseResultResp* resultBaseResultResp;
}

- (BaseResultResp*) defaultInstance;

- (BaseResultRespBuilder*) clear;
- (BaseResultRespBuilder*) clone;

- (BaseResultResp*) build;
- (BaseResultResp*) buildPartial;

- (BaseResultRespBuilder*) mergeFrom:(BaseResultResp*) other;
- (BaseResultRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BaseResultRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (EIMRespHeader*) status;
- (BaseResultRespBuilder*) setStatus:(EIMRespHeader*) value;
- (BaseResultRespBuilder*) setStatusBuilder:(EIMRespHeaderBuilder*) builderForValue;
- (BaseResultRespBuilder*) mergeStatus:(EIMRespHeader*) value;
- (BaseResultRespBuilder*) clearStatus;
@end


// @@protoc_insertion_point(global_scope)
